### PR TITLE
Enable isomalloc_sync by default

### LINKED ISSUE #1964: Enable +isomalloc_sync by default for AMPI
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1964*

---
If running an AMPI application, it's often necessary to pass the runtime option '+isomalloc_sync' to ensure correctness in the face of Address Space Layout Randomization (ASLR).
The current implementation of +isomalloc_sync requires support for a shared file system across nodes, which is common but not universal. It would be nicer if we enabled +isomalloc_sync runtime support by default (on certain builds/systems only?) and added an option to disable it.

### LINKED ISSUE #2043: Add +isomalloc_sync build-time options
*Original issue: https://charm.cs.illinois.edu/redmine/issues/2043*

---
Add two options: one to run with '+isomalloc_sync' by default, another to disable the warning about it completely.
The warning is confusing to users who aren't using AMPI or ULTs at all, and for most systems we want it on by default anyway.

### PR DESCRIPTION
**Pull request by evan-charmworks**
Closes #1964
Closes #2043

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Draft until #2720 is merged

**Comment by matthiasdiener** [comment]
The command line is inverted and renamed, right?

**Comment by evan-charmworks** [comment]
> The command line is inverted and renamed, right?

Yes, now there is `+no_isomalloc_sync`.

**Comment by matthiasdiener** [comment]
> > The command line is inverted and renamed, right?
> 
> Yes, now there is `+no_isomalloc_sync`.

Ok, this could be clarified in the title. Not sure if it necessary to document it in the manual.

**Comment by evan-charmworks** [comment]
> > > The command line is inverted and renamed, right?
> > 
> > 
> > Yes, now there is `+no_isomalloc_sync`.
> 
> Ok, this could be clarified in the title. Not sure if it necessary to document it in the manual.

I'll update the title when merging. If the sync fails we suggest the option to the user.

**Comment by evan-charmworks** [comment]
Added documentation.

**Pull request merged**
