### PR TITLE
Update release notes and version for 6.10.2

### PR DESCRIPTION
**Pull request by rbuch**
Towards #3005.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Just to clarify, the idea is to merge this to master and then cherry pick the commit to the v6.10.2 branch?

**Comment by rbuch** [comment]
> Just to clarify, the idea is to merge this to master and then cherry pick the commit to the v6.10.2 branch?

Yes, exactly that.

**Comment by rbuch** [comment]
Converting to draft to avoid merging until we get a clean autobuild.

**Comment by rbuch** [comment]
Proceeding without a clean autobuild because the patch (#2727) that fixes `megampi` doesn't apply cleanly and is complex enough that it's not worth adding.

**Pull request merged**
