### PR TITLE
CkArray: Fix semantics of initCallback/doneInserting

### PR DESCRIPTION
**Pull request by epmikida**
Array maps previously automatically called doneInserting on the array after initial insertion. This occurred even for arrays with 0 elements. For cases where users then did dynamic insertion and called doneInserting themselves, doneInserting was essentially a no-op (with some messaging). This change makes it so doneInserting is only automatically called for arrays with static insertion.

### CODE REVIEW

**Comment by epmikida** [comment]
Note that this doesn't resolve the doneInsertion synchronization issues that are showing up in AMPI and elsewhere, but it's a step in the right direction, and should in theory at least make those errors less common.

**Review by stwhite91 — APPROVED** [review]

**Comment by epmikida** [comment]
So it turns out this patch has the following issue: static insertion is actually set to false by default, regardless of how the array is created. During core, I'll propose the following changes:

Get rid of the _isStaticInsertion flag, and instead use the method of array creation as the way to set the default value of `CkArrayOptions::staticInsertion`. If I construct my array as follows:
```CProxy_Foo::ckNew(numElements);```
or
```CkArrayOptions opts; opts.setNumInitial(numElements); // numElements != 0```
```CProxy_Foo::ckNew(opts);```
Then we will assume staticInsertion is true. If instead, I use `CProxy_Foo::ckNew();` or use `numElements == 0`, we will assume dynamic insertion.

Both of these assumptions can be overridden by using the existing `CkArrayOptions::setStaticInsertion(bool)` as normal.

With the additional changes in already in this PR, this would cause our semantics to match up with what is already in use and documented in the manual regarding the need/purpose of `doneInserting`.

I don't think this should cause any major issues since it aligns with our current documentation, but discussion here would be helpful as well.

**Review by ericjbohm — DISMISSED** [review]

**Review by stwhite91 — APPROVED** [review]

**Comment by epmikida** [comment]
With the latest commit, this makes it so both doneInserting and initCallback work as expected for most cases. The one remaining issue is for cases where initCallback is used, and there are multiple phases of inserting this will behave weirdly. Granted, even in the old implementation it behaved weirdly in that initCallback meant nothing and would be called multiple times, once for each doneInserting call.

**Comment by epmikida** [comment]
This is ready for review now.

**Review by evan-charmworks — APPROVED** [review]

**Review by stwhite91 — APPROVED** [review]

**Pull request merged**
