### PR TITLE
Remove uth machine layer

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Review by minitu — APPROVED** [review]

**Review by evan-charmworks — CHANGES_REQUESTED** [review]
I don't agree with this PR. We should discuss it in Core.

**Comment by matthiasdiener** [comment]
Ready for review.

**Review by minitu — APPROVED** [review]
Just out of curiosity, how did you find the files related to uth? Did you just grep for uth and CMK_SHARED_VARS_UNIPROCESSOR?

**Comment by matthiasdiener** [comment]
> Just out of curiosity, how did you find the files related to uth? Did you just grep for uth and CMK_SHARED_VARS_UNIPROCESSOR?

I use `grep` (actually `ripgrep`) to search for uth/CMK_UTH etc., and `ripfind` to look for filenames that match 'uth'. In some cases, it is useful to use `unifdef` to resolve changes to`#ifdef` and `#if` automatically, but this wasn't really necessary in this case.

**Comment by matthiasdiener** [comment]
Needs another review.

**Review by ericjbohm — APPROVED** [review]

**Pull request merged**
