### PR TITLE
Examples: Fix size of array allocation in PUP for jacobi2d-2d-decomposition

### PR DESCRIPTION
**Pull request by rbuch**

### CODE REVIEW

**Review by stwhite91 — APPROVED** [review]
It would be nicer to have these be std::vector's

**Comment by matthiasdiener** [comment]
Are the other Jacobi examples not affected?

**Comment by rbuch** [comment]
> Are the other Jacobi examples not affected?

No, the others are correct.

**Comment by rbuch** [comment]
> It would be nicer to have these be std::vector's

Agreed, they probably need even more cleanup than that, but I think that should be another PR.

**Review by matthiasdiener — APPROVED** [review]

**Pull request merged**
