### PR TITLE
bugfix: libcharm build for charm4py should use CMK_SHARED_SUF

### PR DESCRIPTION
**Pull request by ericjbohm**
The makefile hardcoded the filename to libcharm.so, should be libcharm.$CMK_SHARED_SUF to support darwin or other architectures with targets that are not .so.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This PR contains unrelated changes. [95b3371](https://github.com/UIUC-PPL/charm/pull/3796/commits/95b3371c6e48d92e8821be70cb56a828d0b9c5e4) looks good, but I think #3795 is an unrelated issue (#3795 shows an issue with the CMake build system, which does not use `src/scripts/Makefile`).

**Review by matthiasdiener — CHANGES_REQUESTED** [review]
See my comment

**Comment by ericjbohm** [comment]
> See my comment ([#3796 (comment)](https://github.com/UIUC-PPL/charm/pull/3796#issuecomment-2024075902))

Well, someone made the same mistake over in the cmake, but I don't  know where that is.  In any case, this should give people a workaround via buildold.

**Comment by ericjbohm** [comment]
> This PR contains unrelated changes. [95b3371](https://github.com/UIUC-PPL/charm/pull/3796/commits/95b3371c6e48d92e8821be70cb56a828d0b9c5e4) looks good, but I think #3795 is an unrelated issue (#3795 shows an issue with the CMake build system, which does not use `src/scripts/Makefile`).

The unrelated changes are due to my apparently having done this on the wrong branch. No idea why I even had the ofi cxi branch checked out on this laptop.

**Comment by ericjbohm** [comment]
change was made to the wrong branch

**Comment by matthiasdiener** [comment]
> > See my comment ([#3796 (comment)](https://github.com/UIUC-PPL/charm/pull/3796#issuecomment-2024075902))
> 
> Well, someone made the same mistake over in the cmake, 

It's a different issue, in #3795 there is already the correct .dylib extension.

**Pull request closed without merging**
