### PR TITLE
Disable chkpt test in SMP mode

### PR DESCRIPTION
**Pull request by evan-charmworks**
Avoids CI and autobuild failures caused by lack of SMP-awareness in checkpoint/restore code.

See: #3295, #2613, #1955, #1775, #1510

### CODE REVIEW

**Review by epmikida — APPROVED** [review]
May be worth discussing in core ways to better handle features like chkpt, ft, etc. They are marketed as core features of the RTS, but are so lightly tested if at all. I'm not even sure we need separate tests for them. In theory, many of our tests should already be chkpt/ft compatible, and we just need to run them with these features on. Just like we do with SMP.

**Comment by trquinn** [comment]
ChaNGa has a checkpoint test since we use the feature all the time.

**Comment by evan-charmworks** [comment]
> In theory, many of our tests should already be chkpt/ft compatible, and we just need to run them with these features on. 

I don't believe this is the case.

**Comment by epmikida** [comment]
> > In theory, many of our tests should already be chkpt/ft compatible, and we just need to run them with these features on.
> 
> I don't believe this is the case.

Many might be a strong word, but I would hope its a non-empty subset. And if there are not many, maybe that should also be re-evaluated as well.

**Comment by evan-charmworks** [comment]
I just experienced another spurious CI failure due to this test failing in SMP and multicore, in #3297. We should merge this ASAP.

> ChaNGa has a checkpoint test since we use the feature all the time.

Do you use checkpointing in SMP mode?

**Comment by trquinn** [comment]
> I just experienced another spurious CI failure due to this test failing in SMP and multicore, in #3297. We should merge this ASAP.
> 
> > ChaNGa has a checkpoint test since we use the feature all the time.
> 
> Do you use checkpointing in SMP mode?

All the time!

**Pull request closed without merging**
