### PR TITLE
Charmrun: Expand ability to disable ASLR and do so by default

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
I'm not sure why this is using posix_spawn instead of fork/exec. Isn't the personality inherited on an exec call?

**Comment by evan-charmworks** [comment]
> I'm not sure why this is using posix_spawn instead of fork/exec. Isn't the personality inherited on an exec call?

The `_POSIX_SPAWN_DISABLE_ASLR` flag is the only way to disable ASLR at runtime on macOS. I see no reason not to also enable posix_spawn on other platforms that support it, because no functionality is lost by using it instead of fork/exec.

**Comment by matthiasdiener** [comment]
> > I'm not sure why this is using posix_spawn instead of fork/exec. Isn't the personality inherited on an exec call?
> 
> The `_POSIX_SPAWN_DISABLE_ASLR` flag is the only way to disable ASLR at runtime on macOS. I see no reason not to also enable posix_spawn on other platforms that support it, because no functionality is lost by using it instead of fork/exec.

Ok, but please add this as a comment. Is `_POSIX_SPAWN_DISABLE_ASLR` only used in macOS?

**Comment by evan-charmworks** [comment]
> Is `_POSIX_SPAWN_DISABLE_ASLR` only used in macOS?

Yes.

**Comment by matthiasdiener** [comment]
This looks good, but there seem to be some unrelated changes now.

**Comment by evan-charmworks** [comment]
> This looks good, but there seem to be some unrelated changes now.

The extent of the changes to threads.C are adding `// If this crashes, disable ASLR.` comments while keeping line lengths under 72 characters through use of local variables.

**Pull request merged**
