### PR TITLE
ifx support

### PR DESCRIPTION
**Pull request by rscohn2**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
I think this might also need `ifx` support in `./src/arch/common/` (similar to `./src/arch/common/conv-mach-ifort.{h,sh}`).

**Comment by rscohn2** [comment]
Spack adds `ifx` to the `build` command line, and this change was enough for `spack install` to complete without errors. Is there a build command that would let me know if I have done the fortran part of `cc-icx.sh` correctly?

**Comment by rscohn2** [comment]
> Is there a build command that would let me know if I have done the fortran part of `cc-icx.sh` correctly?

I see it now. Building a fortran example.

**Comment by jcphill** [comment]
@rscohn2 Any update on this? I'd support merging as-is if it fixes Spack builds.

**Review by jcphill — APPROVED** [review]

**Comment by matthiasdiener** [comment]
I added an untested stub file for `src/arch/common/conv-mach-ifx.sh` here: https://github.com/rscohn2/charm/commit/4d57d8b05875ced23a1321130617042b71751c6f

Please give it a try.

**Comment by rscohn2** [comment]
I looked at this last month, but there were multiple header files and scripts that potentially needed to be updated. I did not understand how they were used and couldn't find any explanation. Is there a description somewhere? I was helping someone who was using charm, but have not used charm myself.

**Comment by matthiasdiener** [comment]
I've manually tested the current version of this PR with ifx and it worked fine as far as I can see.

**Review by matthiasdiener — APPROVED** [review]

**Review by evan-charmworks — APPROVED** [review]

**Comment by evan-charmworks** [comment]
Currently, merging always uses a `Rebase and merge` strategy. I think we need to clean up and combine the commits on this branch before merging.

**Comment by jcphill** [comment]
> Currently, merging always uses a `Rebase and merge` strategy. I think we need to clean up and combine the commits on this branch before merging.

Please get that done, then, as it's been idle for two weeks.

**Review by stwhite91 — APPROVED** [review]

**Pull request merged**
