### PR TITLE
CHANGES: add info about M1 and removed modules

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Review by Wingpad — APPROVED** [review]

**Comment by evan-charmworks** [comment]
Should this PR also add mention of BG/Q's deprecation?

**Comment by rbuch** [comment]
> Should this PR also add mention of BG/Q's deprecation?

We should make another PR that does that while also adding deprecation messages to the build scripts for the BG/Q target.

**Review by rbuch — APPROVED** [review]

**Comment by matthiasdiener** [comment]
Needs another review.

**Review by Wingpad — APPROVED** [review]

**Comment by matthiasdiener** [comment]
> Should this PR also add mention of BG/Q's deprecation?

Added in #3280.

**Pull request merged**
