### PR TITLE
Add CMK_FDEFS to fix Fortran on i386

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by evan-charmworks** [comment]
So far the Fortran on i386 issues are fixed. The CI is failing due to an unrelated issue in Isomalloc that is exacerbated by the limitations of 32-bit address space.

**Comment by matthiasdiener** [comment]
> So far the Fortran on i386 issues are fixed. The CI is failing due to an unrelated issue in Isomalloc that is exacerbated by the limitations of 32-bit address space.

Does it fail with the old build system too?

**Comment by evan-charmworks** [comment]
> > So far the Fortran on i386 issues are fixed. The CI is failing due to an unrelated issue in Isomalloc that is exacerbated by the limitations of 32-bit address space.
> 
> Does it fail with the old build system too?

I haven't tested, but it's not related to the build process, it's in Isomalloc's code.

**Comment by matthiasdiener** [comment]
> > > So far the Fortran on i386 issues are fixed. The CI is failing due to an unrelated issue in Isomalloc that is exacerbated by the limitations of 32-bit address space.
> > 
> > 
> > Does it fail with the old build system too?
> 
> I haven't tested, but it's not related to the build process, it's in Isomalloc's code.

Yeah, it seems to fail in the same way with buildold.

**Review by matthiasdiener — APPROVED** [review]

**Review by stwhite91 — APPROVED** [review]

**Pull request merged**
