### PR TITLE
cmake: fixes for ChaNGa

### LINKED ISSUE #2863: cmake build system is not installing liveViz.h
With the latest master, a "./build ChaNGa ...." doesn't copy liveViz.h into include, and so ChaNGa fails to build.
Reverting to commit 26216d4526783ab87cc2664be7e8c7ab062aa1ff fixes the problem.

### PR DESCRIPTION
**Pull request by matthiasdiener**
Fixes #2863.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
> Still doesn't work for me.

Is it still not finding liveViz.h ?

**Comment by matthiasdiener** [comment]
When building this branch, I get:

```
$ ls include/liveViz*
include/liveViz.decl.h  include/liveViz.h   include/liveViz3d.decl.h  include/liveVizPoll.decl.h
include/liveViz.def.h   include/liveViz0.h  include/liveViz3d.def.h   include/liveVizPoll.def.h
```

**Comment by trquinn** [comment]
I get:
 git branch
* (HEAD detached at origin/cmake-liveviz)

./build ChaNGa netlrts-linux-x86_64 -j8 -O2
...

ls include/live*
include/liveViz3d.decl.h  include/liveViz.decl.h  include/liveVizPoll.decl.h
include/liveViz3d.def.h   include/liveViz.def.h   include/liveVizPoll.def.h

**Comment by matthiasdiener** [comment]
@trquinn Thanks for the update. Could you try again with the updated branch?

**Comment by trquinn** [comment]
Now "CkCache.h" is not found (perhaps should have checked this earlier.

Also: now the AMPI library is being built, which is not useful for ChaNGa, and generates lots of warnings.

**Comment by trquinn** [comment]
There are still a lot of messages like:
```
pi-io/mpiu_external32.c:117:9: warning: ‘MPI_Unpack_external’ is deprecated: currently unimplemented in AMPI [-Wdeprecated-declarations]
  117 |         mpi_errno = MPI_Unpack_external("external32", tmp_buf, bytes,
      |         ^~~~~~~~~
In file included from ./adio/include/adio.h:72,
                 from mpi-io/mpioimpl.h:15,
                 from mpi-io/mpiu_external32.c:6:
/home1/00333/tg456090/src/charm/ucx-linux-x86_64-smp/bin/../include/ampi_functions.h:651:23: note: declared here
  651 | AMPI_FUNC_NOIMPL(int, MPI_Unpack_external, const char datarep[], const void *inbuf, MPI_Aint insize, MPI_Aint *position, void *outbuf, int outcount, MPI_Datatype datatype)
      |                       ^~~~~~~~~~~~~~~~~~~
/home1/00333/tg456090/src/charm/ucx-linux-x86_64-smp/bin/../include/ampi/mpi.h:30:27: note: in definition of macro ‘AMPI_FUNCPTR’
   30 |   #define AMPI_FUNCPTR(x) x
      |                           ^
/home1/00333/tg456090/src/charm/ucx-linux-x86_64-smp/bin/../include/ampi/mpi.h:1388:19: note: in expansion of macro ‘AMPI_API_DEF’
 1388 | #define AMPI_FUNC AMPI_API_DEF
      |                   ^~~~~~~~~~~~
/home1/00333/tg456090/src/charm/ucx-linux-x86_64-smp/bin/../include/ampi/mpi.h:1389:45: note: in expansion of macro ‘AMPI_FUNC’
 1389 | #define AMPI_FUNC_NOIMPL AMPI_UNIMPLEMENTED AMPI_FUNC
      |                                             ^~~~~~~~~
/home1/00333/tg456090/src/charm/ucx-linux-x86_64-smp/bin/../include/ampi_functions.h:651:1: note: in expansion of macro ‘AMPI_FUNC_NOIMPL’
  651 | AMPI_FUNC_NOIMPL(int, MPI_Unpack_external, const char datarep[], const void *inbuf, MPI_Aint insize, MPI_Aint *position, void *outbuf, int outcount, MPI_Datatype datatype)
      | ^~~~~~~~~~~~~~~~
[100%] No install step for 'romio'
[100%] Completed 'romio'
[100%] Built target romio
```
I've now got an error from another recent change:
```
../charm/bin/../include/conv-autoconfig.h:4:23: error: too many decimal points in number
    4 | #define CHARM_VERSION 6.10.1
      |                       ^~~~~~
DataManager.h:16:5: note: in expansion of macro ‘CHARM_VERSION’
   16 | #if CHARM_VERSION > 60401 && CMK_BALANCED_INJECTION_API
      |     ^~~~~~~~~~~~~
../charm/bin/../include/conv-autoconfig.h:4:23: error: too many decimal points in number
    4 | #define CHARM_VERSION 6.10.1
      |                       ^~~~~~
DataManager.h:280:5: note: in expansion of macro ‘CHARM_VERSION’
  280 | #if CHARM_VERSION > 60401 && CMK_BALANCED_INJECTION_API
      |     ^~~~~~~~~~~~~
```

**Comment by matthiasdiener** [comment]
> There are still a lot of messages like:

Thank you @trquinn for the report. With the current version of this branch, I'm able to build ChaNGa. The AMPI warnings are still there, but I'll address those in a different PR.

**Comment by trquinn** [comment]
It now builds for me as well.
However, there is another version issue, when I run ChaNGa, I get:
```
Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v61001
```
I used to get a git hash in the Commit ID line, which is quite important for reproducing results (and tracking bugs!).  Can we get that back?

**Comment by rbuch** [comment]
> It now builds for me as well.
> However, there is another version issue, when I run ChaNGa, I get:
> 
> ```
> Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
> Charm++> The comm. thread both sends and receives messages
> Converse/Charm++ Commit ID: v61001
> ```
> 
> I used to get a git hash in the Commit ID line, which is quite important for reproducing results (and tracking bugs!). Can we get that back?

Agreed, we need to get this back. Furthermore, the current display seems misleading, I think it should be using `git describe` or something of that ilk so that it uses the most recent tag to reflect that we are currently on something like "v6.11.0-devel-272-g800278a9d".

**Comment by matthiasdiener** [comment]
Version number should be fixed now.

**Comment by trquinn** [comment]
This now looks good.

**Pull request merged**
