### PR TITLE
CI: test build-shared

### PR DESCRIPTION
**Pull request by matthiasdiener**
So far, I think we have no CI/autobuild test with --build-shared.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Test fails with:

```
../../../bin/testrun  ./cxx-fsglobals +p1 +vp2 +balancer RandCentLB ++local
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 0.011 seconds.
Charm++> Running in non-SMP mode: 1 processes (PEs)
Converse/Charm++ Commit ID: b1e2fb6
Charm++ built with internal error checking enabled.
Do not use for performance benchmarking (build without --enable-error-checking to do so).
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (2 sockets x 1 cores x 1 PUs = 2-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
[0] TreeLB in LEGACY MODE support
[0] TreeLB: Using PE_Root tree with: Random 
AMPI> Using fsglobals privatization method.
Beginning round of testing.
Test #01: extern global, in same object
#01 - [0](0) - 0x0001005f1070 - single write - passed
#01 - [1](0) - 0x0001005f1070 - single write - failed
#01 - [0](0) - 0x0001005f1070 - many write - failed
#01 - [1](0) - 0x0001005f1070 - many write - passed
Test #02: static global, in same object
#02 - [0](0) - 0x0001005f107c - single write - passed
#02 - [1](0) - 0x0001005f107c - single write - failed
#02 - [0](0) - 0x0001005f107c - many write - failed
#02 - [1](0) - 0x0001005f107c - many write - passed
Test #03: static local, in same object
#03 - [0](0) - 0x0001005f1080 - single write - passed
#03 - [1](0) - 0x0001005f1080 - single write - failed
#03 - [0](0) - 0x0001005f1080 - many write - failed
#03 - [1](0) - 0x0001005f1080 - many write - passed
Test #04: extern global, in other object
#04 - [0](0) - 0x0001005f1074 - single write - passed
#04 - [1](0) - 0x0001005f1074 - single write - failed
#04 - [0](0) - 0x0001005f1074 - many write - failed
#04 - [1](0) - 0x0001005f1074 - many write - passed
Test #05: static global, in other object
#05 - [0](0) - 0x0001005f1084 - single write - passed
#05 - [1](0) - 0x0001005f1084 - single write - failed
#05 - [0](0) - 0x0001005f1084 - many write - failed
#05 - [1](0) - 0x0001005f1084 - many write - passed
Test #06: static local, in other object
#06 - [0](0) - 0x0001005f1088 - single write - passed
#06 - [1](0) - 0x0001005f1088 - single write - failed
#06 - [0](0) - 0x0001005f1088 - many write - failed
#06 - [1](0) - 0x0001005f1088 - many write - passed
Test #07: extern global, in static library
#07 - [0](0) - 0x0001005f1078 - single write - passed
#07 - [1](0) - 0x0001005f1078 - single write - failed
#07 - [0](0) - 0x0001005f1078 - many write - failed
#07 - [1](0) - 0x0001005f1078 - many write - passed
Test #08: static global, in static library
#08 - [0](0) - 0x0001005f108c - single write - passed
#08 - [1](0) - 0x0001005f108c - single write - failed
#08 - [0](0) - 0x0001005f108c - many write - failed
#08 - [1](0) - 0x0001005f108c - many write - passed
Test #09: static local, in static library
#09 - [0](0) - 0x0001005f1090 - single write - passed
#09 - [1](0) - 0x0001005f1090 - single write - failed
#09 - [0](0) - 0x0001005f1090 - many write - failed
#09 - [1](0) - 0x0001005f1090 - many write - passed
Round of testing complete.
Beginning round of testing.
Test #10: extern global, in same object
#10 - [0](0) - 0x0001005f1070 - single write - passed
#10 - [1](0) - 0x0001005f1070 - single write - failed
#10 - [0](0) - 0x0001005f1070 - many write - failed
#10 - [1](0) - 0x0001005f1070 - many write - passed
Test #11: static global, in same object
#11 - [0](0) - 0x0001005f107c - single write - passed
#11 - [1](0) - 0x0001005f107c - single write - failed
#11 - [0](0) - 0x0001005f107c - many write - failed
#11 - [1](0) - 0x0001005f107c - many write - passed
Test #12: static local, in same object
#12 - [0](0) - 0x0001005f1080 - single write - passed
#12 - [1](0) - 0x0001005f1080 - single write - failed
#12 - [0](0) - 0x0001005f1080 - many write - failed
#12 - [1](0) - 0x0001005f1080 - many write - passed
Test #13: extern global, in other object
#13 - [0](0) - 0x0001005f1074 - single write - passed
#13 - [1](0) - 0x0001005f1074 - single write - failed
#13 - [0](0) - 0x0001005f1074 - many write - failed
#13 - [1](0) - 0x0001005f1074 - many write - passed
Test #14: static global, in other object
#14 - [0](0) - 0x0001005f1084 - single write - passed
#14 - [1](0) - 0x0001005f1084 - single write - failed
#14 - [0](0) - 0x0001005f1084 - many write - failed
#14 - [1](0) - 0x0001005f1084 - many write - passed
Test #15: static local, in other object
#15 - [0](0) - 0x0001005f1088 - single write - passed
#15 - [1](0) - 0x0001005f1088 - single write - failed
#15 - [0](0) - 0x0001005f1088 - many write - failed
#15 - [1](0) - 0x0001005f1088 - many write - passed
Test #16: extern global, in static library
#16 - [0](0) - 0x0001005f1078 - single write - passed
#16 - [1](0) - 0x0001005f1078 - single write - failed
#16 - [0](0) - 0x0001005f1078 - many write - failed
#16 - [1](0) - 0x0001005f1078 - many write - passed
Test #17: static global, in static library
#17 - [0](0) - 0x0001005f108c - single write - passed
#17 - [1](0) - 0x0001005f108c - single write - failed
#17 - [0](0) - 0x0001005f108c - many write - failed
#17 - [1](0) - 0x0001005f108c - many write - passed
Test #18: static local, in static library
#18 - [0](0) - 0x0001005f1090 - single write - passed
#18 - [1](0) - 0x0001005f1090 - single write - failed
#18 - [0](0) - 0x0001005f1090 - many write - failed
#18 - [1](0) - 0x0001005f1090 - many write - passed
Round of testing complete.
36 tests failed.
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: AMPI: Application called MPI_Abort()!

Fatal error on PE 0> AMPI: Application called MPI_Abort()!


real    0m0.036s
user    0m0.009s
sys 0m0.012s
make[3]: *** [test-cxx-fsglobals] Error 1
make[2]: *** [test-privatization] Error 2
make[1]: *** [test-ampi] Error 2
make: *** [test] Error 2
```

**Comment by evan-charmworks** [comment]
> Is this an expected failure @evan-charmworks ?

I don't know why adding `--build-shared` would cause the method to fail. I will try to reproduce it locally.

**Comment by evan-charmworks** [comment]
Passing `--build-shared` to ./build causes `-build-shared` to be passed to charmc, which interferes with the parameters needed to build a PIE shared object for the privatization methods. I will look at fixing charmc so `-build-shared` is not destructive in this way.

**Comment by evan-charmworks** [comment]
#3103 fixes it.

**Review by rbuch — APPROVED** [review]

**Comment by evan-charmworks** [comment]
The `--build-shared` option builds all .o files as `-fPIC` and creates .so files in lib_so, but we would need to pass `-charm-shared` when building the tests in order to actually use the shared objects. That won't work right now, due to difficulties with hwloc and romio. I updated #2735 which will show this.

**Comment by matthiasdiener** [comment]
> The `--build-shared` option builds all .o files as `-fPIC` and creates .so files in lib_so, but we would need to pass `-charm-shared` when building the tests in order to actually use the shared objects. That won't work right now, due to difficulties with hwloc and romio. I updated #2735 which will show this.

Ok. I would still suggest merging this test as it is, as we have been getting bug reports that building charm with --build-shared doesn't work, and we are currently not checking that (see e.g. https://github.com/spack/spack/issues/18460.) I'll add a TODO item regarding `-charm-shared`/#2735 to this PR.

**Review by evan-charmworks — APPROVED** [review]

**Comment by matthiasdiener** [comment]
Needs another review.

**Review by rbuch — APPROVED** [review]

**Pull request merged**
