### PR TITLE
Implement CmiTLS for Apple Silicon

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Split from #3394

Validated manually on Apple Silicon

**Review by matthiasdiener — APPROVED** [review]

**Review by stwhite91 — COMMENTED** [review]
Can you update the TLSglobals documentation in the manual as well? Otherwise LGTM

**Comment by evan-charmworks** [comment]
> Can you update the TLSglobals documentation in the manual as well? Otherwise LGTM

Done. I didn't update the table since it doesn't represent {OS, arch}.

Also, this `Merge when ready` functionality is new to me. Is there no choice between `Rebase and merge` and `Squash and merge` any more?

**Review by stwhite91 — APPROVED** [review]

**Comment by stwhite91** [comment]
> Also, this `Merge when ready` functionality is new to me. Is there no choice between `Rebase and merge` and `Squash and merge` any more?

That's a good question. @rbuch or @matthiasdiener might know?

**Comment by evan-charmworks** [comment]
This is ready to merge, I just want to be sure it will squash.

**Comment by rbuch** [comment]
> > Also, this `Merge when ready` functionality is new to me. Is there no choice between `Rebase and merge` and `Squash and merge` any more?
> 
> That's a good question. @rbuch or @matthiasdiener might know?

The merge queue doesn't let you choose between rebasing and squashing for each PR, it instead has a repo-wide setting of one or the other (it's currently set to rebase, so all PRs will be rebased).

The merge queue helps when merging many PRs since it allows them to be stacked when going through final CI approval rather than having to wait for a PR to be merged and then updating the next one, serializing CI; addressing that was the impetus to try out the merge queue, but it does come with the downside of forcing either only rebase or merge for all PRs. Given that the number of simultaneous PRs we're merging these days is usually not very high, the benefits of the merge queue aren't terribly useful for us in practice, so perhaps we should return to previous merge flow we were using.

**Comment by evan-charmworks** [comment]
For now I've squashed this manually so it can be merged.

> > > Also, this `Merge when ready` functionality is new to me. Is there no choice between `Rebase and merge` and `Squash and merge` any more?
> > 
> > 
> > That's a good question. @rbuch or @matthiasdiener might know?
> 
> The merge queue doesn't let you choose between rebasing and squashing for each PR, it instead has a repo-wide setting of one or the other (it's currently set to rebase, so all PRs will be rebased).
> 
> The merge queue helps when merging many PRs since it allows them to be stacked when going through final CI approval rather than having to wait for a PR to be merged and then updating the next one, serializing CI; addressing that was the impetus to try out the merge queue, but it does come with the downside of forcing either only rebase or merge for all PRs. Given that the number of simultaneous PRs we're merging these days is usually not very high, the benefits of the merge queue aren't terribly useful for us in practice, so perhaps we should return to previous merge flow we were using.

I definitely see the utility of the merge queue. If anything it seems like GitHub could use the feedback that we don't want to give up the choice between squashing and rebasing. Both options have their place. Squashing keeps everything clean during code review since the branch is only added to, while rebasing is important when a patchset is separated into semantic units.

**Pull request merged**
