### PR TITLE
CMake: Fix build on ARM platforms

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Review by matthiasdiener — APPROVED** [review]

**Comment by evan-charmworks** [comment]
Needs one more review

**Review by stwhite91 — APPROVED** [review]

**Comment by matthiasdiener** [comment]
We don't have any kind of automated tests for ARM, right? If we have a machine available, it's easy to install our own Github Actions runner on it for CI.

**Comment by evan-charmworks** [comment]
> We don't have any kind of automated tests for ARM, right? If we have an ARM machine available, it's easy to install our own Github Actions runner on it for CI.

We have Raspberry Pis, but I don't think we want verification to take multiple hours. We might want to look into one of Nvidia's ARM boards.

**Comment by matthiasdiener** [comment]
> > We don't have any kind of automated tests for ARM, right? If we have an ARM machine available, it's easy to install our own Github Actions runner on it for CI.
> 
> We have Raspberry Pis, but I don't think we want verification to take multiple hours. We might want to look into one of Nvidia's ARM boards.

I dunno how slow they are, but could we use them just for building Charm++ (without testing)?

**Comment by rbuch** [comment]
A consortium has a program to provide ARM infrastructure for open source codes here: https://github.com/WorksOnArm/cluster/blob/master/.github/ISSUE_TEMPLATE/custom.md. This might be suitable for what we need.

**Comment by rbuch** [comment]
Separately, we may want to look into getting a Mac Mini or something to be able to test on macOS + ARM.

**Comment by rbuch** [comment]
> > > We don't have any kind of automated tests for ARM, right? If we have an ARM machine available, it's easy to install our own Github Actions runner on it for CI.
> > 
> > 
> > We have Raspberry Pis, but I don't think we want verification to take multiple hours. We might want to look into one of Nvidia's ARM boards.
> 
> I dunno how slow they are, but could we use them just for building Charm++ (without testing)?

I think what we actually have are BeagleBone Blacks. I don't remember quantitatively how slow they are exactly, but they're no speed demons. They're fairly old, so perhaps more modern SBCs are faster. Regardless, I don't think it's worth making them part of the CI, I think they'll be flaky when it comes to storage space, reliability, ease of use, etc.

**Comment by evan-charmworks** [comment]
We have a cluster of 17 Raspberry Pi 3 Model B+ boards at Charmworks.

**Comment by rbuch** [comment]
> We have a cluster of 17 Raspberry Pi 3 Model B+ boards at Charmworks.

Ah, gotcha, then perhaps that's a more reasonable target, I haven't really worked with it.

**Comment by rbuch** [comment]
For the sake of completeness, [Drone Cloud](https://cloud.drone.io/) and TravisCI both support ARM targets for CI, as well.

**Pull request merged**
