### PR TITLE
AMPI: fix exit code handling for bigsim, multicore, ucx, uth

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
> Fails on uth-linux-x86_64:
> 
> ```
> make[3]: Entering directory '/home/evan/charm/uth-linux-x86_64/examples/bigsim/emulator'
> ../../../bin/charmc -language bigsim -g3 -o jacobi3D common.o jacobi3D.C
> jacobi3D.C: In function ‘void outputData(char*)’:
> jacobi3D.C:878:16: error: too few arguments to function ‘void BgShutdown(int)’
>      BgShutdown();
>                 ^
> In file included from jacobi3D.C:10:0:
> ../../../bin/../include/blue.h:206:6: note: declared here
>  void BgShutdown(int exitcode);
>       ^~~~~~~~~~
> ```



> Fails on uth-linux-x86_64:
> 
> ```
> make[3]: Entering directory '/home/evan/charm/uth-linux-x86_64/examples/bigsim/emulator'
> ../../../bin/charmc -language bigsim -g3 -o jacobi3D common.o jacobi3D.C
> jacobi3D.C: In function ‘void outputData(char*)’:
> jacobi3D.C:878:16: error: too few arguments to function ‘void BgShutdown(int)’
>      BgShutdown();
>                 ^
> In file included from jacobi3D.C:10:0:
> ../../../bin/../include/blue.h:206:6: note: declared here
>  void BgShutdown(int exitcode);
>       ^~~~~~~~~~
> ```

Does the update fix this issue?

**Comment by evan-charmworks** [comment]
The build issue is fixed, but the exit test fails:

```
$ make test
../../../bin/testrun  ./exit_explicit 2>&1 ; [ $? -eq 42 ] && echo "exit_explicit test passed." || (echo "exit_explicit test failed (exit code was $?, but expected 42)."; false)
Converse/Charm++ Commit ID: v6.9.0-537-g73d707973
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 6 cores x 2 PUs = 12-way SMP)
Charm++> cpu topology info is gathered in 0.001 seconds.
In application, expecting to exit with exit code 42.
exit_explicit test failed (exit code was 1, but expected 42).
Makefile:20: recipe for target 'test' failed
make: *** [test] Error 1
```

UTH is a non-LRTS layer so it likely needs its own handling, as does PAMI if that has not also been fixed.

**Comment by matthiasdiener** [comment]
> The build issue is fixed, but the exit test fails:
> 
> ```
> $ make test
> ../../../bin/testrun  ./exit_explicit 2>&1 ; [ $? -eq 42 ] && echo "exit_explicit test passed." || (echo "exit_explicit test failed (exit code was $?, but expected 42)."; false)
> Converse/Charm++ Commit ID: v6.9.0-537-g73d707973
> CharmLB> Load balancer assumes all CPUs are same.
> Charm++> Running on 1 hosts (1 sockets x 6 cores x 2 PUs = 12-way SMP)
> Charm++> cpu topology info is gathered in 0.001 seconds.
> In application, expecting to exit with exit code 42.
> exit_explicit test failed (exit code was 1, but expected 42).
> Makefile:20: recipe for target 'test' failed
> make: *** [test] Error 1
> ```
> 
> UTH is a non-LRTS layer so it likely needs its own handling, as does PAMI if that has not also been fixed.

ugh should work now

**Comment by matthiasdiener** [comment]
ready for review.

**Pull request merged**
