### PR TITLE
Fix missing CmiInCommThread

### PR DESCRIPTION
**Pull request by matthiasdiener**
Followup from #2540.

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Should there be one for `CMK_SHARED_VARS_UNIPROCESSOR` too?

**Comment by evan-charmworks** [comment]
Additionally, this patch should `#define CmiInCommThread() (0)` if not SMP

**Comment by matthiasdiener** [comment]
> Additionally, this patch should `#define CmiInCommThread() (0)` if not SMP

Done.

**Comment by matthiasdiener** [comment]
> Should there be one for `CMK_SHARED_VARS_UNIPROCESSOR` too?

Not sure. What should CmiInCommThread() be defined to in this case?

**Comment by matthiasdiener** [comment]
> From this, my guess is that we should just define `#define CmiInCommThread() (0)`?:
> 
> ```c
> #if CMK_SHARED_VARS_UNIPROCESSOR /*Used only by uth- and sim- versions*/
> 
> #define CmiMyPe()              _Cmi_mype
> #define CmiMyRank()            _Cmi_mype
> ```

done

**Pull request merged**
