### PR TITLE
Fix OPTS when rebuilding libmemory and libthreads from tmp

### PR DESCRIPTION
**Pull request by evan-charmworks**
Could merge this for 6.10

### CODE REVIEW

**Comment by matthiasdiener** [comment]
I don't understand this patch. According to the make docs (https://ftp.gnu.org/old-gnu/Manuals/make-3.80/html_node/make_59.html#SEC63)

> The define directive does not expand variable references and function calls in the canned sequence; the `$' characters, parentheses, variable names, and so on, all become part of the value of the variable you are defining.

Isn't that the correct behavior here?

**Comment by evan-charmworks** [comment]
A single `$` will cause the variable to expand at the time of the `define`, while a double `$$` will cause it to expand when the define is `call`ed.

My guess is something to do with this at the bottom of the Makefile:

```
# If OPTS was not defined, use the build time options
export OPTS ?= $(OPTSATBUILDTIME)
ifeq ($(strip $(OPTS)),)
$(warning Variable OPTS is defined to an empty string. Are you sure this is what you want?)
endif
```

**Comment by matthiasdiener** [comment]
> A single `$` will cause the variable to expand at the time of the `define`, while a double `$$` will cause it to expand when the define is `call`ed.

But doesn't this contradict the manual that I quoted above?

I tested this with the following Makefile:

``` makefile
MEM_DEPS=foo_mem_deps
CHARMC=foo_charmc


define libmem
mytarget: $$(MEM_DEPS) $2
	@echo $$(CHARMC) -I. -o libmemory-$1.o $3
	@echo $$(CHARMC) -I. -o $$@ $3 libmemory-$1.o
endef

all: mytarget

foo_mem_deps:
first_arg:
second_arg:
third_arg:

$(eval $(call libmem,first_arg,second_arg,third_arg))
```

Writing `$(MEM_DEPS)` or `$$(MEM_DEPS)` doesn't seem to make a difference. This is with GNU make 3.81.

**Comment by evan-charmworks** [comment]
Needs one more review

**Pull request merged**
