### PR TITLE
AMPI: Clean up ROMIO configure step parameters

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Review by stwhite91 — APPROVED** [review]

**Review by trquinn — CHANGES_REQUESTED** [review]
build ChaNGa still doesn't work.

**Comment by matthiasdiener** [comment]
> build ChaNGa still doesn't work.

Is it the same error message as before? Also, does `./buildold ...` work?

**Comment by evan-charmworks** [comment]
If the commits I just pushed don't fix the issue, I'm stumped.

**Review by trquinn — APPROVED** [review]
It now builds!

**Review by stwhite91 — APPROVED** [review]

**Pull request merged**
