### PR TITLE
Collection of fixes to address CI issues

### PR DESCRIPTION
**Pull request by rbuch**

### CODE REVIEW

**Review by evan-charmworks — APPROVED** [review]

**Comment by evan-charmworks** [comment]
Charm4py and Multicore Darwin tracing failures are both spurious, in the chkpt test (#3296, #3295). UCX failed when trying to build libucx's Java bindings.

**Review by matthiasdiener — DISMISSED** [review]

**Review by evan-charmworks — APPROVED** [review]

**Comment by evan-charmworks** [comment]
UCX has a new failure that I've seen twice now:

```
make[5]: Entering directory '/home/runner/work/charm/charm/ucx-linux-x86_64-openpmix/examples/charm++/zerocopy/entry_method_post_api/reg/multiplePostedBuffers'
../../../../../../bin/testrun  +p4 ./multiplePostedBuffers 32 +balancer RotateLB 

Running on 4 processors:  ./multiplePostedBuffers 32 +balancer RotateLB 
charmrun>  /usr/bin/setarch x86_64 -R  mpirun -np 4  ./multiplePostedBuffers 32 +balancer RotateLB 
Charm++> Running in non-SMP mode: 4 processes (PEs)
Converse/Charm++ Commit ID: v6.11.0-beta1-137-g9fb5dcc10
Isomalloc> Synchronized global address space.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 2 cores x 1 PUs = 2-way SMP)
Charm++> cpu topology info is gathered in 0.020 seconds.
[0] TreeLB in LEGACY MODE support
[0] TreeLB: Using PE_Root tree with: Rotate 
sdagRun: Iteration 1 completed
sdagRun: Iteration 2 completed
sdagRun: Iteration 3 completed
sdagRun: Iteration 4 completed
sdagRun: Iteration 5 completed
sdagRun: Iteration 6 completed
sdagRun: Iteration 7 completed
sdagRun: Iteration 8 completed
sdagRun: Iteration 9 completed
sdagRun: Iteration 10 completed
sdagRun: Iteration 11 completed
sdagRun: Iteration 12 completed
sdagRun: Iteration 13 completed
sdagRun: Iteration 14 completed
sdagRun: Iteration 15 completed
sdagRun: Iteration 16 completed
sdagRun: Iteration 17 completed
sdagRun: Iteration 18 completed
sdagRun: Iteration 19 completed
sdagRun: Iteration 20 completed
sdagRun: Iteration 21 completed
sdagRun: Iteration 22 completed
sdagRun: Iteration 23 completed
sdagRun: Iteration 24 completed
sdagRun: Iteration 25 completed
sdagRun: Iteration 26 completed
sdagRun: Iteration 27 completed
sdagRun: Iteration 28 completed
sdagRun: Iteration 29 completed
sdagRun: Iteration 30 completed
sdagRun: Iteration 31 completed
sdagRun: Iteration 32 completed
sdagRun: Iteration 33 completed
sdagRun: Iteration 34 completed
sdagRun: Iteration 35 completed
sdagRun: Iteration 36 completed
sdagRun: Iteration 37 completed
sdagRun: Iteration 38 completed
sdagRun: Iteration 39 completed
sdagRun: Iteration 40 completed
[fv-az180-662:400395:0:400395] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x55555718eb78)
==== backtrace (tid: 400395) ====
 0  /lib/libucs.so.0(ucs_handle_error+0x2a4) [0x7ffff7f241c4]
 1  /lib/libucs.so.0(+0x2639f) [0x7ffff7f2439f]
 2  /lib/libucs.so.0(+0x266d4) [0x7ffff7f246d4]
 3  /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7ffff78fd210]
 4  ./multiplePostedBuffers(_Z12LrtsSendFunciiiPci+0x29) [0x5555557b1ce9]
 5  ./multiplePostedBuffers(CldEnqueue+0x111) [0x5555557ee0b1]
 6  ./multiplePostedBuffers(_ZNK10CkCallback4sendEPv+0x474) [0x555555705204]
 7  ./multiplePostedBuffers(_ZN14CkReductionMgr15finishReductionEv+0x3e1) [0x5555557649d1]
 8  ./multiplePostedBuffers(CkDeliverMessageFree+0x2e) [0x5555556dc48e]
 9  ./multiplePostedBuffers(_Z15_processHandlerPvP11CkCoreState+0x1a30) [0x5555556e51e0]
10  ./multiplePostedBuffers(CsdScheduleForever+0xcd) [0x5555557885dd]
11  ./multiplePostedBuffers(CsdScheduler+0x35) [0x555555788935]
12  ./multiplePostedBuffers(ConverseInit+0x542) [0x5555557b33c2]
13  ./multiplePostedBuffers(charm_main+0x2d) [0x55555576dfad]
14  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff78de0b3]
15  ./multiplePostedBuffers(_start+0x2e) [0x55555564201e]
=================================
```

**Comment by nitbhat** [comment]
I tried debugging the ucx failure with tmate and I am getting the following stack trace: (the destPe/destNode is suspicious as seen in frame 0 and frame 1). 
```
(gdb) bt
#0  0x00005555557d6aa9 in UcxSendMsg (
    cb=0x5555557d47e0 <UcxTxReqCompleted(void*, ucs_status_t)>, tag=0,
    msg=0x555555bf5820 “\300”, size=192, destPE=<optimized out>,
    destNode=<optimized out>)
    at /home/runner/work/charm/charm/src/arch/ucx/machine.C:553
#1  LrtsSendFunc (destNode=1435891840, destPE=<optimized out>, size=192,
    msg=0x555555bf5820 “\300", mode=1)
    at /home/runner/work/charm/charm/src/arch/ucx/machine.C:553
#2  0x0000555555812e71 in CldEnqueue (pe=1435891840, msg=<optimized out>,
    infofn=37) at /home/runner/work/charm/charm/src/conv-ldb/cldb.rand.C:129
#3  0x0000555555729eb4 in CkCallback::send (this=0x555555bf5898,
    msg=0x555555bf5860)
    at /home/runner/work/charm/charm/src/ck-core/ckcallback.C:364
#4  0x0000555555789661 in CkReductionMgr::finishReduction (this=0x555555bd05f0)
    at /home/runner/work/charm/charm/src/ck-core/ckreduction.C:682
#5  0x0000555555788f08 in CkReductionMgr::addContribution (
    this=0x555555bd05f0, m=0x555555bf5940)
#6  0x0000555555666391 in zerocopyObject::nextStep (this=0x555555bd9410)
    at multiplePostedBuffers.C:163
#7  0x00005555556661c3 in zerocopyObject::sdagZeroCopySent (
    this=0x555555bd9410, m=0x555555be2900) at multiplePostedBuffers.C:143
#8  0x000055555565f455 in CkIndex_zerocopyObject::_call_sdagZeroCopySent_CkDataM
sg (impl_msg=0x555555be2900, impl_obj_void=0x555555bd9410)
    at simpleZeroCopy.def.h:724
#9  0x00005555557011fe in CkDeliverMessageFree (epIdx=149, msg=0x555555be2900,
    obj=<optimized out>) at /home/runner/work/charm/charm/src/ck-core/ck.C:549
#10 0x0000555555742abc in CkLocRec::invokeEntry (this=0x555555bd95f0,
    obj=0x555555bd9410, msg=0x555555be2900, epIdx=149, doFree=<optimized out>)
    at /home/runner/work/charm/charm/src/ck-core/cklocation.C:2246
#11 0x0000555555709912 in CkMigratable::ckInvokeEntry (doFree=<optimized out>,
    msg=<optimized out>, epIdx=<optimized out>, this=<optimized out>)
    at /home/runner/work/charm/charm/src/ck-core/ckmigratable.h:79
#12 _processArrayEltMsg (env=0x555555be28c0, ck=0x555555bb0500)
    at /home/runner/work/charm/charm/src/ck-core/ck.C:1177
#13 _processHandler (converseMsg=<optimized out>, ck=0x555555bb0500)
    at /home/runner/work/charm/charm/src/ck-core/ck.C:1270
#14 0x00005555557ad44d in CmiHandleMessage (msg=<optimized out>)
    at /home/runner/work/charm/charm/src/conv-core/convcore.C:1695
#15 CsdScheduleForever ()
    at /home/runner/work/charm/charm/src/conv-core/convcore.C:1942
#16 0x00005555557ad7a5 in CsdScheduler (maxmsgs=maxmsgs@entry=-1)
    at /home/runner/work/charm/charm/src/conv-core/convcore.C:1881
#17 0x00005555557d8182 in ConverseRunPE (everReturn=0)
    at /home/runner/work/charm/charm/src/arch/util/machine-common-core.C:1609
#18 ConverseInit (argc=<optimized out>, argv=<optimized out>,
fn=fn@entry=0x5555--Type <RET> for more, q to quit, c to continue without paging--
    55792e90 <_initCharm(int, char**)>,
    usched=usched@entry=0, initret=initret@entry=0)
    at /home/runner/work/charm/charm/src/arch/util/machine-common-core.C:1524
#19 0x0000555555792c3d in charm_main (argc=<optimized out>,
    argv=<optimized out>)
    at /home/runner/work/charm/charm/src/ck-core/init.C:1739
#20 0x00007ffff78dd0b3 in __libc_start_main (
    main=0x55555565c7e0 <main(int, char**)>, argc=4, argv=0x7fffffffc968,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffc958) at ../csu/libc-start.c:308
#21 0x000055555565d39e in _start ()
    at /home/runner/work/charm/charm/src/ck-core/ck.C:32
```

Basically, the `contribute(compReductionCb);` call in `nextStep()` triggers the segfault because in frame 3 of the stack trace, when the chare PE is to be determined, there's some garbage value in d.chare.onPE, which goes onto cause the crash in UcxSendMsg. 
```
(gdb) frame 3
#3  0x0000555555729eb4 in CkCallback::send (this=0x555555bf5898,
    msg=0x555555bf5860)
    at /home/runner/work/charm/charm/src/ck-core/ckcallback.C:364
364                     CkSendMsg(d.chare.ep, msg, &d.chare.id);
(gdb) print d.chare.ep
$1 = 144
(gdb) print d.chare
$2 = {ep = 144, id = {onPE = 1435891840, objPtr = 0x0}, refnum = 0,
  hasRefnum = false}
```
The compReductionCb is set to reduction target Main::done, which doesn't even migrate, so I'm wondering where the incorrect PE is being populated from.

**Comment by evan-charmworks** [comment]
I can reproduce the segfault locally and it happens as least as far back as 4e15c48d1499a038a414849b3fc548b3a21b0ac8. ASan does not help.

**Comment by nitbhat** [comment]
I wasn't able to reproduce this bug locally on a lab machine.

**Comment by nitbhat** [comment]
Thanks to the tmate session, I was able to reproduce and debug this. The bug was in the zerocopy multiplePostedBuffers example because of incorrect callback construction. The fix is in https://github.com/UIUC-PPL/charm/pull/3305. 

I'll revert the tmate debugging patches now.

**Review by evan-charmworks — APPROVED** [review]

**Review by matthiasdiener — APPROVED** [review]

**Pull request merged**
