### PR TITLE
Support IBM Power architecture with UCX

### LINKED ISSUE #2788: Enable UCX build on IBM Power9
Currently UCX build is not supported on IBM Power9 machines, including OLCF Summit and LLNL Lassen.
This would require having `ucx-linux-ppc` & `ucx-linux-ppc64le` folders implemented in `arch`.

Related to using GPUDirect RDMA for inter-GPU communication.

### PR DESCRIPTION
**Pull request by minitu**
Closes #2788.

`cc-gcc.*` and `cc-xlc.*` were copied from `pamilrts-linux-ppc64le`, and `conv-mach*` files from `ucx-linux-x86_64`.

Builds successfully with `./build charm++ ucx-linux-ppc64le smp -j --with-production`, but tests fail with the following error:
```
[0] Stack Traceback:
------- Partition 0 Processor 0 Exiting: Called CmiAbort ------
Reason: UCX: UcxInitEps: runtime_kvs_put error failed: 5
  [0:0] verify 0x101e8454 CmiAbort
  [0:1] verify 0x101f4c00 LrtsInit(int*, char***, int*, int*)
  [0:2] verify 0x101f80c8 ConverseInit
  [0:3] verify 0x100af980 charm_main
  [0:4] verify 0x10098e98 main
  [0:5] libc.so.6 0x200000885200
  [0:6] libc.so.6 0x2000008853f4 __libc_start_main
------- Partition 0 Processor 0 Exiting: Called CmiAbort ------
Reason: UCX: UcxInitEps: runtime_kvs_put error failed: 5
[0] Stack Traceback:
  [0:0] verify 0x101e8454 CmiAbort
  [0:1] verify 0x101f4c00 LrtsInit(int*, char***, int*, int*)
  [0:2] verify 0x101f80c8 ConverseInit
  [0:3] verify 0x100af980 charm_main
  [0:4] verify 0x10098e98 main
  [0:5] libc.so.6 0x200000885200
  [0:6] libc.so.6 0x2000008853f4 __libc_start_main
```

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Errors look similar to #2477.

**Comment by minitu** [comment]
@matthiasdiener Interesting, I thought the files that I just copied over were either incorrect or incomplete.
On LLNL Lassen it fails with jsrun and charmrun:

**Comment by matthiasdiener** [comment]
> On LLNL Lassen it fails with both `jsrun` and `charmrun` (even with `++local`):

Just to clarify, running with `charmrun` but without `++local`, as well as running the binary directly, results in the same error?

Can you try to build with `ompipmix`?

**Comment by minitu** [comment]
Without `++local`:
```
choi18@lassen710:1darray$ ./charmrun +p1 ./hello +ppn 1        

Running on 1 processors:  ./hello +ppn 1 
cmpirun -lsf -poll -no_smp -gm_long 200000 ./hello +ppn 1
./charmrun: line 170: cmpirun: command not found
```

Binary:
```
choi18@lassen710:1darray$ ./hello
------- Partition 0 Processor 0 Exiting: Called CmiAbort ------
Reason: UCX: UcxInitEps: runtime_kvs_put error failed: 5
[0] Stack Traceback:
  [0:0] hello 0x101d9a94 CmiAbort
  [0:1] hello 0x101e6240 LrtsInit(int*, char***, int*, int*)
  [0:2] hello 0x101e9708 ConverseInit
  [0:3] hello 0x100a4d60 charm_main
  [0:4] hello 0x100975c8 main
  [0:5] libc.so.6 0x200000785200 
  [0:6] libc.so.6 0x2000007853f4 __libc_start_main
```

**Comment by minitu** [comment]
With `ompipmix`, tests using `jsrun` pass with one caveat: `export LD_LIBRARY_PATH=$HOME/openmpi-4.0.1/install/lib:$LD_LIBRARY_PATH` is needed.
Otherwise you get the following error:
```
choi18@lassen710:1darray$ jsrun -n1 -a1 -c1 -r1 ./hello +ppn 1 +pemap L0,4
./hello: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
```

With the LD_LIBRARY_PATH set:
```
choi18@lassen710:1darray$ ./hello
NS  rank 0: PMIx_Init failed: -44
------- Partition 0 Processor 0 Exiting: Called CmiAbort ------
Reason: UCX: runtime_init failed: -1
[0] Stack Traceback:
  [0:0] hello 0x101d91a4 CmiAbort
  [0:1] hello 0x101e5434 LrtsInit(int*, char***, int*, int*)
  [0:2] hello 0x101e8140 ConverseInit
  [0:3] hello 0x100a4860 charm_main
  [0:4] hello 0x100970d8 main
  [0:5] libc.so.6 0x200000b35200 
  [0:6] libc.so.6 0x200000b353f4 __libc_start_main
```
```
choi18@lassen710:1darray$ jsrun -n1 -a1 -c1 -r1 ./hello +ppn 1 +pemap L0,4
Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.11.0-devel-193-ga9befbc6b
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map (logical indices): 0,4
Charm++> Running on 1 hosts (2 sockets x 20 cores x 4 PUs = 160-way SMP)
Charm++> cpu topology info is gathered in 0.002 seconds.
Running Hello on 1 processors for 5 elements
Hello 0 created
Hello 1 created
Hello 2 created
Hello 3 created
Hello 4 created
Main::initDone reached
Hi[17] from element 0
Hi[18] from element 1
Hi[19] from element 2
Hi[20] from element 3
Hi[21] from element 4
All done
[Partition 0][Node 0] End of program
```
```
choi18@lassen710:1darray$ jsrun -n2 -a1 -c1 -r2 ./hello +ppn 1 +pemap L0,4
Charm++> Running in SMP mode: 2 processes, 1 worker threads (PEs) + 1 comm threads per process, 2 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.11.0-devel-193-ga9befbc6b
Isomalloc> Synchronized global address space.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map (logical indices): 0,4
Charm++> Running on 1 hosts (2 sockets x 20 cores x 4 PUs = 160-way SMP)
Charm++> cpu topology info is gathered in 0.003 seconds.
Running Hello on 2 processors for 5 elements
Hello 0 created
Hello 1 created
Hello 2 created
Main::initDone reached
Hello 3 created
Hello 4 created
Hi[20] from element 3
Hi[17] from element 0
Hi[18] from element 1
Hi[19] from element 2
Hi[21] from element 4
All done
[Partition 0][Node 0] End of program
```
```
choi18@lassen710:1darray$ jsrun -n2 -a1 -c1 -r1 ./hello +ppn 1 +pemap L0,4
Charm++> Running in SMP mode: 2 processes, 1 worker threads (PEs) + 1 comm threads per process, 2 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.11.0-devel-193-ga9befbc6b
Isomalloc> Synchronized global address space.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity PE-core map (logical indices): 0,4
Charm++> Running on 2 hosts (2 sockets x 20 cores x 4 PUs = 160-way SMP)
Charm++> cpu topology info is gathered in 0.003 seconds.
Running Hello on 2 processors for 5 elements
Hello 3 created
Hello 4 created
Hi[20] from element 3
Hello 0 created
Hello 1 created
Hello 2 created
Main::initDone reached
Hi[17] from element 0
Hi[18] from element 1
Hi[19] from element 2
Hi[21] from element 4
All done
[Partition 0][Node 0] End of program
```

**Comment by matthiasdiener** [comment]
> With `ompipmix`, tests using `jsrun` pass with one caveat: `export LD_LIBRARY_PATH=$HOME/openmpi-4.0.1/install/lib:$LD_LIBRARY_PATH` is needed.

Great, that's what I would expect. We do a similar `export LD_LIBRARY_PATH...` for the UCX CI (https://github.com/UIUC-PPL/charm/blob/master/.github/workflows/ucx.yml)

**Comment by minitu** [comment]
> Great, that's what I would expect. We do a similar `export LD_LIBRARY_PATH...` for the UCX CI (https://github.com/UIUC-PPL/charm/blob/master/.github/workflows/ucx.yml)

We should add the `export LD_LIBRARY_PATH` thing to the documentation - I'll submit a separate patch for that once this gets merged in.

One thing I'm not sure about this patch is if the `cc-gcc.*` and `cc-xlc.*` files are necessary. I'm guessing they are needed when the user explicitly chooses the compiler to be `gcc` or `xlc`?

**Comment by minitu** [comment]
Btw, it looks like UCX **requires** a version of PMI? There are a bunch of PMI calls in `ucx/machine.C`. If this is the case, the documentation should clarify that PMI is a prerequisite of the UCX build.

**Comment by matthiasdiener** [comment]
> Btw, it looks like UCX **requires** a version of PMI? There are a bunch of PMI calls in `ucx/machine.C`. If this is the case, the documentation should clarify that PMI is a prerequisite of the UCX build.

Yes, I believe it requires PMI. @nitbhat had added instructions to the manual regarding UCX/PMI (https://charm.readthedocs.io/en/latest/charm++/manual.html#ucx), but we could probably make them more prominent in the README.

**Comment by nitbhat** [comment]
> > Btw, it looks like UCX **requires** a version of PMI? There are a bunch of PMI calls in `ucx/machine.C`. If this is the case, the documentation should clarify that PMI is a prerequisite of the UCX build.
> 
> Yes, I believe it requires PMI. @nitbhat had added instructions to the manual regarding UCX/PMI (https://charm.readthedocs.io/en/latest/charm++/manual.html#ucx), but we could probably make them more prominent in the README.

Yeah, it uses PMI. However, the default version (without specifying ompipmix uses Simple PMI, which is available in the charm source code). If the user wishes to use other PMI options like Slurm PMI or PMIx, they would have to pass a path to it (typically in `--basedir`). 

I think setting `LD_LIBRARY_PATH` is not required when passing `--basedir`. But maybe you can confirm that?

**Comment by minitu** [comment]
@nitbhat I see, it should be fine if simple PMI is used as the default (which didn't work on Lassen). `LD_LIBRARY_PATH` was required even with `--basedir`, at least for PMIx which is the one I used and worked on Lassen.

**Comment by minitu** [comment]
I think this patch can get merged in now, please review.

**Comment by matthiasdiener** [comment]
> LGTM, but I'll save approvals for others with access to Power machines to test.

I'll test this on Lassen now.

> > We should add the `export LD_LIBRARY_PATH` thing to the documentation - I'll submit a separate patch for that once this gets merged in.
> 
> For that patch, it may be possible to instead resolve the LD_LIBRARY_PATH issue by passing `-Wl,-rpath,$HOME/openmpi-4.0.1/install/lib` at link time.

Also, isn't this only an issue since we are installing OpenMPI manually?

**Comment by minitu** [comment]
@matthiasdiener Yes I believe the LD_LIBRARY_PATH change is only needed because OpenMPI was installed manually. If OpenMPI is already set up and available on the system I don't think it would be necessary.

**Comment by stwhite91** [comment]
> Worked on Lassen.

Does AMPI migration work on ppc64le? We have a separate issue open for that, it just needs another round of testing: https://github.com/UIUC-PPL/charm/issues/1774

**Comment by matthiasdiener** [comment]
> > Worked on Lassen.
> 
> Does AMPI migration work on ppc64le? We have a separate issue open for that, it just needs another round of testing: #1774

Oh, I didn't even build AMPI. Let me try that. In any case, this patch is probably useful to have.

**Comment by matthiasdiener** [comment]
> > > Worked on Lassen.
> > 
> > 
> > Does AMPI migration work on ppc64le? We have a separate issue open for that, it just needs another round of testing: #1774
> 
> Oh, I didn't even build AMPI. Let me try that. In any case, this patch is probably useful to have.

I ran `make test` in tests/ampi a few times and the tests seem to run fine.

**Pull request merged**
