### PR TITLE
jacobi: do not use VLA

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Surely there is a better option than three-deep std::vector. Would it be difficult to replace this with a 1D vector and replace accesses with a macro for the index that does multiplication?

**Comment by matthiasdiener** [comment]
> Surely there is a better option than three-deep std::vector. Would it be difficult to replace this with a 1D vector and replace accesses with a macro for the index that does multiplication?

Hmm, what's the issue with a three-deep std::vector? This seems such an uncritical part of the code that replacing them with macro indexing or nested mallocs appears to be more trouble than it's worth.

**Comment by evan-charmworks** [comment]
> > Surely there is a better option than three-deep std::vector. Would it be difficult to replace this with a 1D vector and replace accesses with a macro for the index that does multiplication?
> 
> Hmm, what's the issue with a three-deep std::vector? This seems such an uncritical part of the code that replacing the vectors with macro indexing or nested mallocs appears to be more trouble than it's worth.

It, like nested mallocs, are poor form. Fortunately macro indexing was not hard to put in place.

**Comment by matthiasdiener** [comment]
This is the type of code I was hoping to avoid:

```c++
std::vector<int> jmap(num_chare_x * num_chare_y * num_chare_z);
#define jmap_3d(x, y, z) (jmap[(x) * num_chare_y * num_chare_z + (y) * num_chare_z + (z)])
```

> It, like nested mallocs, are poor form.

You didn't say why it is poor form. I'd say that nested vectors are clearer and more readable, while performance seems to be mostly a wash (see e.g. https://scicomp.stackexchange.com/questions/3159/is-it-a-good-idea-to-use-vectorvectordouble-to-form-a-matrix-class-for-high). Like I mentioned above, performance isn't really an issue here anyways, since the code is run at initialization only.

**Comment by evan-charmworks** [comment]
> You didn't say why it is poor form.

It took me a while to find, but I was thinking of issue #1315.

**Comment by matthiasdiener** [comment]
> > You didn't say why it is poor form.
> 
> It took me a while to find, but I was thinking of issue #1315.

For #1315, I do agree that flat arrays are the better choice due to the performance sensitivity and the fact that the arrays get used throughout the whole execution. I'd say this would be overkill for the arrays in question here.

As an aside, the code in #1315 seems to have been changed already, so that issue might be closed now?

**Comment by matthiasdiener** [comment]
Ready for review.

**Comment by matthiasdiener** [comment]
Needs another review.

**Pull request merged**
