### PR TITLE
Add within node broadcast functionality to PAMI

### PR DESCRIPTION
**Pull request by epmikida**

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Does uth also need this code?

**Comment by epmikida** [comment]
> Does uth also need this code?

Yes that is possible. I'm not sure how many of the machine layers rewrite their own broadcast functions.

**Comment by epmikida** [comment]
> Fixes pami compile, not sure if bug exists other layers.

Do the tests pass as well? Specifically tests/charm++/within_node

**Comment by nitbhat** [comment]
```
./shmem/machine.C:void CmiSyncBroadcastFn(int size, char *msg)
./sim/machine.C:void CmiSyncBroadcastFn(int size,  char *msg)
./uth/machine.C:void CmiSyncBroadcastFn(int size, char *msg)
```

These layers don't use LRTS and would need their own within node bcast fn.

**Comment by jcphill** [comment]
I'm actually getting segfaults on Summit for simplearrayhello now.

**Comment by jcphill** [comment]
Segfaults…

**Comment by evan-charmworks** [comment]
> Nevermind. The segfaults are in --with-debug, while --with-production works fine.

That still sounds concerning. Do these segfaults predate the introduction of WithinNodeBroadcast?

**Pull request merged**
