### PR TITLE
Embed hwloc into libconverse

### LINKED ISSUE #2599: automake: warning: am_libhwloc_embedded_la_rpath was already defined in condition TRUE, which includes condition !HWLOC_BUILD_STANDALONE
Building Charm++ results in the following warning message on multiple platforms (see e.g. https://github.com/spack/spack/issues/11125, https://lists.cs.illinois.edu/lists/arc/charm/2019-06/msg00008.html, https://my.cdash.org/viewBuildError.php?buildid=1722945):
```
autoreconf
autoheader
automake: warning: am_libhwloc_embedded_la_rpath was already defined in condition TRUE, which includes condition !HWLOC_BUILD_STANDALONE ...
configure.ac:2973: ... 'am_libhwloc_embedded_la_rpath' previously defined here
```

### PR DESCRIPTION
**Pull request by evan-charmworks**
Fixes #2599

### CODE REVIEW

**Comment by evan-charmworks** [comment]
This is WIP. It works for buildold but not for CMake. The current problem is that `file(GLOB hwloc-objects ${CMAKE_BINARY_DIR}/hwloc-prefix/src/hwloc-build/hwloc/*.o)` runs during configure time instead of after the hwloc target builds. I'm not sure how much CMake hackery it will take to get these objects added to the converse target.

**Comment by matthiasdiener** [comment]
> This is WIP. It works for buildold but not for CMake. The current problem is that `file(GLOB hwloc-objects ${CMAKE_BINARY_DIR}/hwloc-prefix/src/hwloc-build/hwloc/*.o)` runs during configure time instead of after the hwloc target builds. I'm not sure how much CMake hackery it will take to get these objects added to the converse target.

Instead of globbing, why not just list them manually? You might also have to add SET_SOURCE_FILES_PROPERTIES like here: https://stackoverflow.com/questions/38609303/how-to-add-prebuilt-object-files-to-executable-in-cmake

**Comment by evan-charmworks** [comment]
> Instead of globbing, why not just list them manually?

I was hoping to avoid that, because such a list would be fragile with regard to different platforms, configuration options, hwloc version updates. For example, topology-{linux,darwin,windows}.o and topology-cuda.o.

**Comment by matthiasdiener** [comment]
> > Instead of globbing, why not just list them manually?
> 
> I was hoping to avoid that, because such a list would be fragile with regard to different platforms, configuration options, and hwloc version updates. For example, topology-{linux,darwin,windows}.o and topology-cuda.o.

Ok, fair. Can you check - does it work to add the .a instead of the .o?

**Comment by evan-charmworks** [comment]
> Ok, fair. Can you check - does it work to add the .a instead of the .o?

If I add the .a to the converse target and also add SET_SOURCE_FILES_PROPERTIES for it, it shows up in the build line for libconverse.a (shown by `VERBOSE=1 make`), but charmc does not do anything with it and linking hello still fails.

**Comment by matthiasdiener** [comment]
> > Instead of globbing, why not just list them manually?
> 
> I was hoping to avoid that, because such a list would be fragile with regard to different platforms, configuration options, and hwloc version updates. For example, topology-{linux,darwin,windows}.o and topology-cuda.o.

I've implemented something without globbing. Are we relay that platform-dependent? All I could see was `topology-{linux,darwin,windows}.o` CUDA support is always disabled.

**Comment by evan-charmworks** [comment]
Windows:
```
make[2]: *** No rule to make target 'hwloc-prefix/src/hwloc-build/hwloc/base64.o', needed by 'lib/libconverse.a'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:624: CMakeFiles/converse.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Maybe we need to define the objects as outputs of the hwloc target somehow.

**Comment by matthiasdiener** [comment]
> Windows:
> 
> ```
> make[2]: *** No rule to make target 'hwloc-prefix/src/hwloc-build/hwloc/base64.o', needed by 'lib/libconverse.a'.  Stop.
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:624: CMakeFiles/converse.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ```

Should be fixed now.

> Maybe we need to define the objects as outputs of the hwloc target somehow.

Unfortunately, I think there is no other way then listing them in the way I did.

**Comment by evan-charmworks** [comment]
> Unfortunately, I think there is no other way then listing them in the way I did.

I didn't think about the file extension difference. I was wondering why this error happened even though we specify that the converse target depends on the hwloc target. I think this is sufficient.

**Comment by evan-charmworks** [comment]
Ready for review

**Review by matthiasdiener — APPROVED** [review]

**Review by minitu — APPROVED** [review]

**Pull request merged**
