### PR TITLE
Avoid hang during Isomalloc-Sync

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by evan-charmworks** [comment]
CPU affinity has now been cleaned up, resolving the CI hang introduced by the first commit. @trquinn Ready for testing.

**Review by trquinn — CHANGES_REQUESTED** [review]
It still hangs.

**Comment by evan-charmworks** [comment]
> It still hangs.

Okay, I can reproduce this, but now it happens at program exit instead of during initialization. I will debug further.

**Comment by evan-charmworks** [comment]
There are still two hangs.

One is somewhere in the implementation of `CmiNodeReduceStruct`. I have verified that Isomalloc-Sync does everything correctly, but the reduction never completes and calls `CmiIsomallocSyncReductionHandler`. `CmiAddressSpaceRegionMerge` and `CmiAddressSpaceRegionPup` are called fewer times than normal before the hang (6 vs. 8, 60 vs. 62; `+n32 ++ppn 4`).

The other is at exit. The worker threads on most nodes are in the `CmiYield` loop in `realConverseExit`, while the comm thread is stuck in an `MPI_Barrier` inside the block of code that handles exiting. I still need to find what node is not participating in the barrier and where.

It's rare to reproduce them, taking a few minutes of iterations before hitting, and it's a coin flip for which hang is encountered.

**Comment by evan-charmworks** [comment]
@trquinn I fixed a data race in the CmiNodeReduce API that Isomalloc-Sync uses and have not seen any of the hangs or crashes since. Ready for another round of testing.

**Review by trquinn — APPROVED** [review]
It doesn't hang!

**Review by stwhite91 — APPROVED** [review]
Avoid squashing at merge, or else make the commit message more descriptive.

Good work tracking this down Evan, and thanks Toms for the testing!

**Pull request merged**
