### PR TITLE
Add optional parameter for freeing CkCallback in GPUManager WorkRequest

### LINKED ISSUE #2232: Add optional parameter for freeing CkCallback in GPUManager WorkRequest
Brought up in ChaNGa meeting, Tom found a memory leak.
Currently the user is responsible for freeing the CkCallback object after it gets invoked, but we should augment the functions used to set the callback to include an optional parameter for freeing it.

Related ChaNGa patch (based on Charm++ 6.9.0, should be updated after this change gets merged in): https://charm.cs.illinois.edu/gerrit/#/c/cosmo/changa/+/5180/

### PR DESCRIPTION
**Pull request by minitu**
Closes #2232

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Failure was in `examples/charm++/zerocopy/entry_method_post_api/prereg/simpleZeroCopy`

**Comment by nitbhat** [comment]
I'll examine this failure and try to identify the cause.

**Comment by nitbhat** [comment]
I ran the test iteratively on a lab machine and wasn't able to reproduce the bug. How many cores does the Travis VM use? Is it possible to interactively get such a VM to have similar conditions for bug reproduction? @matthiasdiener @evan-charmworks

**Comment by evan-charmworks** [comment]
Are the contents of `charm/.travis.yml` able to answer your questions?

**Comment by nitbhat** [comment]
I just see a -j3 option, but don't really see any other configuration options.

**Comment by evan-charmworks** [comment]
Are you using the MPI machine layer?

**Comment by nitbhat** [comment]
Yes, I am.

**Comment by matthiasdiener** [comment]
@nitbhat Travis VMs have 2 SMT threads (ie, a single physical core).

**Comment by minitu** [comment]
@nitbhat @matthiasdiener Looks like the check passed, can this be merged?

**Comment by nitbhat** [comment]
Thanks @matthiasdiener. I'll open an issue for this and try to investigate it separately.

**Pull request merged**
