### PR TITLE
Fix the -Wl,-rpath option for shared build

### PR DESCRIPTION
**Pull request by marmistrz**

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Something is going wrong now, and hwloc_embedded.so doesn't actually get build.

`./build charm++ netlrts-linux-x86_64 --build-shared -j8 -g3 && cd netlrts-linux-x86_64/tests/charm++/simplearrayhello/ && make OPTS="-g3 -charm-shared" -Bj8`

**Comment by evan-charmworks** [comment]
@marmistrz What exactly was the issue that this PR resolved for you?

**Comment by evan-charmworks** [comment]
I think I just encountered it:

```
configure:7026: checking whether the C compiler works
configure:7048: gcc  -DCMK_GFORTRAN   -rpath /home/evan/charm/netlrts-linux-x86_64/lib_so conftest.c  >&5
gcc: error: unrecognized command line option '-rpath'
configure:7052: $? = 1
configure:7090: result: no
```

**Comment by marmistrz** [comment]
> I think I just encountered it:
> 
> ```
> configure:7026: checking whether the C compiler works
> configure:7048: gcc  -DCMK_GFORTRAN   -rpath /home/evan/charm/netlrts-linux-x86_64/lib_so conftest.c  >&5
> gcc: error: unrecognized command line option '-rpath'
> configure:7052: $? = 1
> configure:7090: result: no
> ```

Yes, this was precisely the issue I was fixing. I was unable to build AMPI with `--build-shared` without this patch.

**Pull request merged**
