### PR TITLE
AMPI cleanup: move MPI_Waitall implementation into ampiParent::waitall()

### PR DESCRIPTION
**Pull request by stwhite91**
*Original date: 2019-05-03 19:18:19*
*Original PR: https://charm.cs.illinois.edu/gerrit/4143*

---

Change-Id: I520a6d8598a0ec6e0dc553ebaeb7b1a481d52c95

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Needs a force-push

**Comment by stwhite91** [comment]
Ready for review

**Comment by evan-charmworks** [comment]
Should ampiParent::waitall return a parent pointer for refreshing purposes? I don't see where it currently returns anything other than MPI_SUCCESS.

**Comment by stwhite91** [comment]
> Should ampiParent::waitall return a parent pointer for refreshing purposes? I don't see where it currently returns anything other than MPI_SUCCESS.

Yes, done

**Pull request merged**
