### PR TITLE
charmc #2617: pass through rsp files

### LINKED ISSUE #2617: ampicxx doesn't properly recognize -isystem and *.rsp response files
While trying to compile GROMACS using AMPI 6.9.0, the following command crashes ampicxx:
```
[  0%] Building CXX object src/gromacs/CMakeFiles/lmfit_objlib.dir/__/external/lmfit/lmmin.cpp.o
cd /home/marcin/gromacs/gromacs-2019.3/build-ampi-mpi/src/gromacs && /home/marcin/charm-6.9.0/mpi-linux-x86_64/bin//ampicxx  -DGMX_DOUBLE=0 -DHAVE_CONFIG_H -I/home/marcin/gromacs/gromacs-2019.3/build-ampi-mpi/src/external/build-fftw/fftwBuild-prefix/include -I/home/marcin/gromacs/gromacs-2019.3/build-ampi-mpi/src -isystem /home/marcin/gromacs/gromacs-2019.3/src/external/thread_mpi/include -I/home/marcin/gromacs/gromacs-2019.3/src  -mavx2 -mfma    -std=c++11    -funroll-all-loops -fexcess-precision=fast   -fPIC   -o CMakeFiles/lmfit_objlib.dir/__/external/lmfit/lmmin.cpp.o -c /home/marcin/gromacs/gromacs-2019.3/src/external/lmfit/lmmin.cpp
Fatal Error by charmc in directory /home/marcin/gromacs/gromacs-2019.3/build-ampi-mpi/src/gromacs
   file with unrecognized extension /home/marcin/gromacs/gromacs-2019.3/src/external/thread_mpi/include
charmc exiting...
```

The culprit is clearly the following argument:
```
-isystem /home/marcin/gromacs/gromacs-2019.3/src/external/thread_mpi/include
```
which is mistakenly considered an input source file and not an include directory.

### PR DESCRIPTION
**Pull request by matthiasdiener**
Partially fixes #2617.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
@marmistrz: Could you please test this patch?

**Comment by marmistrz** [comment]
When trying to build Gromacs using this branch, the linking fails:
```
[ 42%] Linking CXX shared library ../../lib/libgromacs_mpi.so                                                                                                                                 
cd /home/marcin/gromacs/gromacs-2019.3/build-ampi-mpi/src/gromacs && /usr/bin/cmake -E cmake_link_script CMakeFiles/libgromacs.dir/link.txt --verbose=1                                       
/home/marcin/charm/mpi-linux-x86_64/bin//ampicxx -fPIC  -mavx2 -mfma   -DAMPI_RENAME_EXIT=0 -std=c++11   -O3 -DNDEBUG -funroll-all-loops -fexcess-precision=fast      -shared -Wl,-soname,libg
romacs_mpi.so.4 -o ../../lib/libgromacs_mpi.so.4.0.0 @CMakeFiles/libgromacs.dir/objects1.rsp -Wl,-rpath,"\$ORIGIN/../lib" /usr/lib/x86_64-linux-gnu/libhwloc.so -ldl -lrt ../external/build-ff
tw/fftwBuild-prefix/lib/libfftw3f.a -fopenmp -lm                                                                                                                                              
/usr/bin/ld: cannot find -lmoduletcharm                                                                                                                                                       
/usr/bin/ld: cannot find -lmoduleampi                                                                                                                                                         
/usr/bin/ld: cannot find -lmoduletcharmmain                                                                                                                                                   
/usr/bin/ld: cannot find -lampiromio                                                                                                                                                          
/usr/bin/ld: cannot find -lampi-compat                                                                                                                                                        
/usr/bin/ld: cannot find -lmoduletcharmmain                                                                                                                                                   
/usr/bin/ld: cannot find -lmoduleampi                                                                                                                                                         
/usr/bin/ld: cannot find -lmoduletcharm                                                                                                                                                       
/usr/bin/ld: cannot find -ltcharm-compat                                                                                                                                                      
collect2: error: ld returned 1 exit status                                                                                                                                                    
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!  Failed to compile Charm++ shared library. You can disable shared   !!
!!  lib compilation by providing --no-build-shared build option like:  !!
!!     ./build charm++ netlrts-linux --no-build-shared -O              !!
!!  or reexecute this charmc command with the --no-build-shared option !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Fatal Error by charmc in directory /home/marcin/gromacs/gromacs-2019.3/build-ampi-mpi/src/gromacs
   Command mpicxx  -rdynamic   -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX  -o ../../lib/libgromacs_mpi.so.4.0.0   -fPIC  -mavx2  -mfma  -std=c++11 -O3  -funroll-all-loops  -fexcess-precision=fa$t  -pthread   -fopenmp -fpic -shared    -lmoduletcharm -lmoduleampi -lmoduletcharmmain /usr/lib/x86_64-linux-gnu/libhwloc.so -ldl -lrt ../external/build-fftw/fftwBuild-prefix/lib/libfftw3f.$ -lm -lampiromio -lampi-compat -Wl,-soname,libgromacs_mpi.so.4 -Wl,-rpath,/../lib -lmoduletcharmmain -lmoduleampi -lmoduletcharm -ltcharm-compat  -lz -lm  returned error code 1
charmc exiting...
src/gromacs/CMakeFiles/libgromacs.dir/build.make:19822: recipe for target 'lib/libgromacs_mpi.so.4.0.0' failed
make[2]: *** [lib/libgromacs_mpi.so.4.0.0] Error 1
make[2]: Leaving directory '/home/marcin/gromacs/gromacs-2019.3/build-ampi-mpi'
CMakeFiles/Makefile2:2764: recipe for target 'src/gromacs/CMakeFiles/libgromacs.dir/all' failed
make[1]: *** [src/gromacs/CMakeFiles/libgromacs.dir/all] Error 2
make[1]: Leaving directory '/home/marcin/gromacs/gromacs-2019.3/build-ampi-mpi'
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by evan-charmworks** [comment]
It looks like you're trying to build a shared object. What happens if you try rebuilding with the `--build-shared` flag so that shared libraries of Charm++ and AMPI are built?

**Comment by marmistrz** [comment]
I needed to use the fix from #2631 to be able to build charm in shared mode at all.
Now the linker fails to find Gromacs symbols:
```
[ 98%] Linking CXX executable ../../bin/template                                                                                                                                              
cd /home/marcin/gromacs/gromacs-2019.3/build-ampi-mpi/share/template && /usr/bin/cmake -E cmake_link_script CMakeFiles/template.dir/link.txt --verbose=1                                      
/home/marcin/charm/mpi-linux-x86_64/bin//ampicxx   -mavx2 -mfma   -DAMPI_RENAME_EXIT=0 -std=c++11    -funroll-all-loops -fexcess-precision=fast       CMakeFiles/template.dir/template.cpp.o  
-o ../../bin/template -Wl,-rpath,"\$ORIGIN/../lib" ../../lib/libgromacs_mpi.so.4.0.0 -fopenmp -lm                                                                                             
CMakeFiles/template.dir/template.cpp.o: In function `AnalysisTemplate::AnalysisTemplate()':                                                                                                   
template.cpp:(.text+0x137): undefined reference to `gmx::TrajectoryAnalysisModule::TrajectoryAnalysisModule()'                                                                                
template.cpp:(.text+0x196): undefined reference to `gmx::AnalysisNeighborhood::AnalysisNeighborhood()'                                                                                        
template.cpp:(.text+0x1a6): undefined reference to `gmx::AnalysisData::AnalysisData()'                                                                                                        
template.cpp:(.text+0x1d4): undefined reference to `gmx::TrajectoryAnalysisModule::registerAnalysisDataset(gmx::AnalysisData*, char const*)'                                                  
template.cpp:(.text+0x1f9): undefined reference to `gmx::AnalysisData::~AnalysisData()'                                                                                                       
template.cpp:(.text+0x20e): undefined reference to `gmx::AnalysisNeighborhood::~AnalysisNeighborhood()'                                                                                       
template.cpp:(.text+0x23f): undefined reference to `gmx::TrajectoryAnalysisModule::~TrajectoryAnalysisModule()'   
```

but `nm` doesn't list them either:
```
$ nm ./lib/libgromacs_mpi.so.4.0.0
0000000000201020 B __bss_start
0000000000201020 b completed.7697
                 w __cxa_finalize
0000000000000470 t deregister_tm_clones
0000000000000500 t __do_global_dtors_aux
0000000000200e68 t __do_global_dtors_aux_fini_array_entry
0000000000201018 d __dso_handle
0000000000200e70 d _DYNAMIC
0000000000201020 D _edata
0000000000201028 B _end
000000000000054c T _fini
0000000000000540 t frame_dummy
0000000000200e60 t __frame_dummy_init_array_entry
0000000000000558 r __FRAME_END__
0000000000201000 d _GLOBAL_OFFSET_TABLE_
                 w __gmon_start__
0000000000000430 T _init
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
0000000000000558 r __offload_funcs_end
0000000000000558 r __offload_func_table
0000000000000558 r __offload_vars_end
0000000000000558 r __offload_var_table
00000000000004b0 t register_tm_clones
0000000000201020 d __TMC_END__

```
Indeed, the library built using AMPI is suspiciously small:
```
marcin@azathoth:~/gromacs/gromacs-2019.3/build-ampi-mpi$ du -h lib/libgromacs_mpi.so.4.0.0 
8,0K    lib/libgromacs_mpi.so.4.0.0
```
in comparison to the AMPI-free build.
```
marcin@azathoth:~/gromacs/gromacs-2019.3/build-ampi-mpi$ du -h ../build/lib/libgromacs_mpi.so.4.0.0 
25M     ../build/lib/libgromacs_mpi.so.4.0.0
```
If you'd like to reproduce my issue, you can download Gromacs 2019.3 and then:
```
mkdir build
cd build 
cmake -DCMAKE_C_COMPILER=$AMPI_ROOT/ampicc -DCMAKE_CXX_COMPILER=$AMPI_ROOT/ampicxx -DCMAKE_CXX_FLAGS='-DAMPI_RENAME_EXIT=0' -DGMX_MPI=ON -DGMX_BUILD_OWN_FFTW=ON ..
make
```

**Comment by matthiasdiener** [comment]
@marmistrz Can you please also provide your full AMPI `./build` command?

**Comment by marmistrz** [comment]
@matthiasdiener `./build AMPI mpi-linux-x86_64 --with-production --build-shared -j8`

**Comment by matthiasdiener** [comment]
Has my +1.

**Pull request merged**
