### PR TITLE
Bug #480: Make migrateMe() more forgiving by executing it asynchronously

### PR DESCRIPTION
**Pull request by pplimport**
*Original author: Gerrit Code Review*
*Original date: 2014-07-14 19:07:58*
*Original PR: https://charm.cs.illinois.edu/gerrit/195*

---

The API routine `void migrateMe(int toPe)' has historically been very
unforgiving, in that any member access after it's called could result in
undefined behavior (reading/writing members of an object that's been
deleted). This is particularly pernicious in combination with SDAG code, in
which the user may not have written any code after the call, but the generated
code has to touch member fields to implement subsequent control flow.

There's nothing really fundamental about running this method perfectly
synchronously - the important bit is that the object migrate as ordered with no
further direction or runtime system mediation. So, add a bare entry method
ckEmigrate() that does only the inline emigration call, and nothing else, and
turn migrateMe() into an asynchronous invocation of that.

To add this everywhere requires some C++11 trickery in the present
implementation. Alternative implementations that are similarly clean are
welcome.

Change-Id: I7a200b7232bf39c5619fe2bc7f62c5097dc7ff03

### CODE REVIEW

**Comment by juanjgalvez** [comment]
For places inside the runtime that call migrateMe, like lb framework and maybe others like ckevacuation, I assume we still want to call migrateMe directly and not schedule it as an entry method. It doesn't pose a problem for lb framework, and if you are migrating many objects it is more efficient to call directly.

Although I'm not sure which is the exact migrate function that gets called from the lb framework.

**Comment by evan-charmworks** [comment]
After rebasing this patch, all tests complete with my assertion in `CkArray::recvBroadcast` from #2231 in place. We should still evaluate whether any uses of `migrateMe` in runtime code should be changed.

**Comment by evan-charmworks** [comment]
I reviewed all calls to `migrateMe` in the runtime found no need to change any of them. I was able to replace the `migrateDelayed` entry method in TCharm with the general `ckEmigrate` added here.

**Comment by juanjgalvez** [comment]
Do you know what the load balancing framework calls to make chares migrate? I spent some time trying to track it down but didn't get to the bottom of it. I think it might be using function pointers which made it hard to track.

**Comment by evan-charmworks** [comment]
A pseudo-backtrace would look like

```
void CkLocMgr::emigrate(CkLocRec *, int)
void CkLocRec::migrateMe(int)
inline void CkMigratable::ckMigrate(int)
entry void ArrayElement::ckEmigrate(int)
inline void CBase_*::migrateMe(int)
```

It looks like `CkLocMgr::emigrate` is the highest-level point that handles the details of migration.

**Comment by juanjgalvez** [comment]
Ok, I just saw that when the lb framework wants to migrate, the call leads to `CkLocRec::migrateMe` without going through `ArrayElement::migrateMe`.

Another concern is if there are applications making use of migrateMe, and if the patch could break them in some obscure way. I assume most applications that migrate objects will use the lb framework.

**Comment by evan-charmworks** [comment]
I don't see any function calls to `ArrayElement::migrateMe` in NAMD, ChaNGa, or OpenAtom.

**Comment by ericjbohm** [comment]
NAMD migration is an application level thing that doesn’t use ArrayElement at all.

**Pull request merged**
