### PR TITLE
CMake: Output simplearrayhello objects to its own folder

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
What's the reason for the change? I was thinking not to compile in the simplearrayhello/ folder in order not to confuse the user .

**Comment by evan-charmworks** [comment]
@matthiasdiener My only concern is that the files are generated in CMAKE_SOURCE_DIR/* instead of CMAKE_BINARY_DIR/* (like Metis was previously). I'm not attached to this way of fixing that.

**Comment by matthiasdiener** [comment]
> @matthiasdiener My only concern is that the files are generated in CMAKE_SOURCE_DIR/* instead of CMAKE_BINARY_DIR/* (like Metis was previously). I'm not attached to this way of fixing that.

Which files are you talking about? Nothing related to simplearrayhello should be generated in `CMAKE_SOURCE_DIR`. it should generate: 
- netlrts-darwin-x86_64/CMakeFiles/hello.dir/tests/charm++/simplearrayhello/hello.C.o
- netlrts-darwin-x86_64/bin/hello
- netlrts-darwin-x86_64/include/hello.{decl, def}.h

**Comment by evan-charmworks** [comment]
My mistake.

**Pull request closed without merging**
