### PR TITLE
run docs through CI

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
@minitu : Could you please check what we can do about this error:

`
/home/runner/work/charm/charm/doc/faq/manual.rst:1665:undefined label: gpumanager (if the link has no caption the label must precede a section header)
`

**Comment by minitu** [comment]
@matthiasdiener #3091

**Comment by evan-charmworks** [comment]
@matthiasdiener @minitu 
```
Warning, treated as error:
/home/runner/work/charm/charm/doc/faq/manual.rst:1665:undefined label: sec-gpu
```

**Comment by matthiasdiener** [comment]
> ```
> Warning, treated as error:
> /home/runner/work/charm/charm/doc/faq/manual.rst:1665:undefined label: sec-gpu
> ```

Great illustration on why we need CI ;-)

Fixed.

**Review by rbuch — APPROVED** [review]

**Review by minitu — APPROVED** [review]

**Pull request merged**
