### PR TITLE
cmake: do not add -std=c++11 to opts_cxx

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Nevermind, this is unlikely to be correct. @epmikida, can you post the command line and output of :
- a `charmc -verbose` command that fails (with the new build system)
- a `charmc -verbose` command that succeeds (with the old build system)

**Comment by epmikida** [comment]
> Nevermind, this is unlikely to be correct. @epmikida, can you post the command line and output of:
> 
> * a `charmc -verbose` command that fails (with the new build system)
> * a `charmc -verbose` command that succeeds (with the old build system)

Updated https://github.com/UIUC-PPL/charm/issues/2839 with the output you were looking for. In summary, the `-no-use-new-std` and `-use-new-std` don't seem to have any effect, and the `./buildold` never causes charmc to add `-std=c++11`, where as `./build` always adds it. Trying out this change now.

**Comment by epmikida** [comment]
This patch does seem to fix the issue I was seeing.
`./build charm++ mpi-linux-x86_64 --build-shared -j8` no longer causes charmc to add `-std=c++11`. The output from `-verbose`:

`charmc -c hello.C -verbose`

```
Verbose mode set
OpenMP support not enabled
charmc> ----------- Module dependency search complete ------------
charmc> All libraries are: -L../../../bin/../lib -lckmain -lck -lmemory-default -lthreads-default -lconv-machine -lconv-core -ltmgr -lconv-util -lconv-partition -lhwloc_embedded -lm -lmemory-default -lthreads-default -lldb-rand -lconv-ldb -lckqt -lz -ldl -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm ../../../bin/../lib/conv-static.o
Compiling hello.C
charmc: Executing rm -f hello.o hello.f.o
charmc: Executing mpicxx -fPIC -DCMK_GFORTRAN -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX -I../../../bin/../include -D__CHARMC__=1 -U_FORTIFY_SOURCE -fno-stack-protector -fno-lifetime-dse -c hello.C -o hello.o
charmc> No target object-- finished
rm -f moduleinit18119.C moduleinit18119.o
```

**Comment by matthiasdiener** [comment]
Closing this, as the workaround in #2839 seems to have worked.

**Pull request closed without merging**
