### PR TITLE
Add nokeep:1 field to some missed out conv message headers

### PR DESCRIPTION
**Pull request by nitbhat**

### CODE REVIEW

**Comment by jcphill** [comment]
Looks like an unrelated spurious failure.

**Comment by nitbhat** [comment]
I've restarted the job.

**Comment by jcphill** [comment]
The failure was probably an actual race condition etc. somewhere.

**Comment by epmikida** [comment]
Is it possible to see what the failing test was, or once a branch is closed is all the Travis data deleted?

**Comment by nitbhat** [comment]
I think @matthiasdiener knows the answer to that.

**Comment by matthiasdiener** [comment]
You should still be able to see old Travis builds: https://travis-ci.org/UIUC-PPL/charm/builds/548777022

**Pull request merged**
