### PR TITLE
Fix Fortran Attribute Getters for AMPI Built-ins

### PR DESCRIPTION
**Pull request by Wingpad**
This (patch) fixes segfaults related to the AMPI Fortran shim wherein pointers were being used in an incorrect manner. 

image

(GDB trace of the error as it occurs in ADCIRC+AMPI.)

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Are you sure the problem is in AMPI and not in ADCIRC, especially given that the error is in the about_to_migrate callback written specifically for AMPI? We have seen problems in those before. The last time I modified these getters in AMPI itself, I tested them with the attached test cases and verified that their general behavior was the same among AMPI, OpenMPI, and MPICH. Won't the Fortran one crash with this changeset?

[mpi-builtin-attributes.cpp.txt](https://github.com/UIUC-PPL/charm/files/5832488/mpi-builtin-attributes.cpp.txt)
[mpi-builtin-attributes.f90.txt](https://github.com/UIUC-PPL/charm/files/5832489/mpi-builtin-attributes.f90.txt)

**Comment by Wingpad** [comment]
Considering that the `result` variable is entirely internal here and _specifically_ where the crash is occurring, I am inclined to believe that the issue is within AMPI (and not ADCIRC). Without this patch, this code is attempting to set the value of an undefined pointer and that is what is causing the segfault. I tested that example with this patch, and it executes normally:
    
    ➜  workspace ampif90 mpi-builtin-attributes.f90 -o mpi-builtin-attributes-f90.mpich -g3
    ➜  workspace mpirun.ampi ./mpi-builtin-attributes-f90.mpich
               0 MPI_TAG_UB              11411628
               0 MPI_HOST              11411632
               0 MPI_IO              11411636
               0 MPI_WTIME_IS_GLOBAL              11411640
               0 MPI_APPNUM              11411644
               0 MPI_LASTUSEDCODE              11411648
               0 MPI_UNIVERSE_SIZE              11411652

**Comment by evan-charmworks** [comment]
Your paste looks like it is printing parts of pointers as integers.

The output should something look like this:

```
$ charm/multicore-linux-x86_64/bin/mpirun.ampi -np 1 ./mpi-builtin-attributes-f90.ampi
           0 MPI_TAG_UB           1073741824
           0 MPI_HOST                   -2
           0 MPI_IO                    0
           0 MPI_WTIME_IS_GLOBAL                    0
           0 MPI_APPNUM                    0
           0 MPI_LASTUSEDCODE                   53
           0 MPI_UNIVERSE_SIZE                    1
$ mpirun.mpich -np 1 ./mpi-builtin-attributes-f90.mpich
           0 MPI_TAG_UB            268435455
           0 MPI_HOST                   -1
           0 MPI_IO                   -2
           0 MPI_WTIME_IS_GLOBAL                    0
           0 MPI_APPNUM                    0
           0 MPI_LASTUSEDCODE           1073741823
           0 MPI_UNIVERSE_SIZE                    0
$ mpirun.openmpi -np 1 ./mpi-builtin-attributes-f90.openmpi
           0 MPI_TAG_UB           2147483647
           0 MPI_HOST                   -2
           0 MPI_IO                   -1
           0 MPI_WTIME_IS_GLOBAL                    0
           0 MPI_APPNUM                    0
           0 MPI_LASTUSEDCODE                   92
           0 MPI_UNIVERSE_SIZE                    1
```

**Comment by matthiasdiener** [comment]
For reference, the previous patch for this was #3070 I believe.

**Comment by Wingpad** [comment]
Oh, I see. Our internal AMPI properties are defined differently... and are not addresses:

      case AMPI_MY_WTH:           *(int *)attribute_val = CkMyPe();     return true;
      case AMPI_NUM_WTHS:         *(int *)attribute_val = CkNumPes();   return true;
      case AMPI_MY_PROCESS:       *(int *)attribute_val = CkMyNode();   return true;
      case AMPI_NUM_PROCESSES:    *(int *)attribute_val = CkNumNodes(); return true;

ADCIRC is trying to dereference `AMPI_MY_WTH` which is a simple integer and not an address. How can we handle these consistently?

**Comment by Wingpad** [comment]
Without this patch, adding this to the example:

      call MPI_Comm_get_attr(MPI_COMM_WORLD, AMPI_MY_WTH, attrval, flag, ierr)
      print *, myrank, "AMPI_MY_WTH", attrval

Causes a segfault like the one in ADCIRC:

    ➜  workspace mpirun.ampi ./mpi-builtin-attributes-f90.ampi
               0 MPI_TAG_UB            1073741824
               0 MPI_HOST                    -2
               0 MPI_IO                     0
               0 MPI_WTIME_IS_GLOBAL                     0
               0 MPI_APPNUM                     0
               0 MPI_LASTUSEDCODE                    53
               0 MPI_UNIVERSE_SIZE                     1
    ------------- Processor 0 Exiting: Caught Signal ------------
    Reason: segmentation violation
    Suggestion: Try running with '++debug', or linking with '-memory paranoid' (memory paranoid requires '+netpoll' at runtime).
    [0] Stack Traceback:
      [0:0] mpi-builtin-attributes-f90.ampi 0x7698d9
      [0:1] libpthread.so.0 0x7ffff4514390
      [0:2] mpi-builtin-attributes-f90.ampi 0x5915b5 mpi_comm_get_attr_
      [0:3] mpi-builtin-attributes-f90.ampi 0x4e17d9 mpi_main_
      [0:4] mpi-builtin-attributes-f90.ampi 0x4f85f3 AMPI_threadstart
      [0:5] mpi-builtin-attributes-f90.ampi 0x4e97b1
      [0:6] mpi-builtin-attributes-f90.ampi 0x72b472 CthStartThread
      [0:7] mpi-builtin-attributes-f90.ampi 0x72c20f make_fcontext
    Fatal error on PE 0> segmentation violation

**Comment by Wingpad** [comment]
I have updated this patch so it demonstrates the correct behaviors for our built-in attributes; using a stack-allocated integer as a "temporary buffer" of sorts such that `result` points to a valid address for the AMPI attributes. The output is now:

                 0 MPI_TAG_UB            1073741824
                 0 MPI_HOST                    -2
                 0 MPI_IO                     0
                 0 MPI_WTIME_IS_GLOBAL                     0
                 0 MPI_APPNUM                     0
                 0 MPI_LASTUSEDCODE                    53
                 0 MPI_UNIVERSE_SIZE                     1
                 0 AMPI_MY_WTH                     0
      [Partition 0][Node 0] End of program

**Comment by matthiasdiener** [comment]
> I have updated this patch so it demonstrates the correct behaviors for our built-in attributes; using a stack-allocated integer as a "temporary buffer" of sorts such that `result` points to a valid address for the AMPI attributes. The output is now:
> 
> ```
>              0 MPI_TAG_UB            1073741824
>              0 MPI_HOST                    -2
>              0 MPI_IO                     0
>              0 MPI_WTIME_IS_GLOBAL                     0
>              0 MPI_APPNUM                     0
>              0 MPI_LASTUSEDCODE                    53
>              0 MPI_UNIVERSE_SIZE                     1
>              0 AMPI_MY_WTH                     0
>   [Partition 0][Node 0] End of program
> ```

Just to be clear, will this stack-allocated variable be valid long enough for the application to fetch the attr?

**Comment by Wingpad** [comment]
> Just to be clear, will this stack-allocated variable be valid long enough for the application to fetch the attr?

Yes, `*result` is dereferenced within the scope of the function so `tmp` hasn't been deallocated yet.

**Review by evan-charmworks — APPROVED** [review]

**Review by matthiasdiener — APPROVED** [review]

**Pull request merged**
