### PR TITLE
Update hwloc to v2.1.0

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Since this changes hwloc's API, there are a few things we should consider:
- Are Charm++/AMPI applications allowed to use hwloc directly if they want to? 
- Do we support mixing our hwloc with an external hwloc?

**Comment by evan-charmworks** [comment]
> * Are Charm++/AMPI applications allowed to use hwloc directly if they want to?

It looks like we expose hwloc.h in our include folder. I would discourage this though. 

Note that I didn't need to change our code that makes use of hwloc for this update.

> * Do we support mixing our hwloc with an external hwloc?

Yes, see #1895.

**Comment by matthiasdiener** [comment]
> > * Are Charm++/AMPI applications allowed to use hwloc directly if they want to?
> 
> It looks like we expose hwloc.h in our include folder. 

So in case the application requires another version of hwloc.h, there might be conflicts?

> Note that I didn't need to change our code that makes use of hwloc for this update.

Ok, but there have been substantial API changes in 2.0: https://www.open-mpi.org/projects/hwloc/doc/v2.1.0/a00343.php

**Comment by stwhite91** [comment]
As long as the API changes don't affect our current usage, I think the upgrade should be merged on its own, and any other issues cleaned up in separate commits

**Pull request merged**
