### PR TITLE
Add assertion to CkArray::recvBroadcast deliver loop

### PR DESCRIPTION
**Pull request by evan-charmworks**
*Original date: 2019-05-07 16:24:02*
*Original PR: https://charm.cs.illinois.edu/gerrit/5165*

---

Change-Id: I817eb1f728bb13255e59cd48c367edabc714d460

### CODE REVIEW

**Comment by stwhite91** [comment]
Won't this effectively disallow broadcasts to ckDestroy?

**Comment by evan-charmworks** [comment]
If this assertion trips, that means that an out-of-bounds access was about to happen, which implies an implementation defect.

**Comment by juanjgalvez** [comment]
I think a broadcast to ckdestroy won't work correctly right now. I think it could skip some elements.

**Comment by stwhite91** [comment]
We may want to change the documentation on ckDestroy() or open a bug for the bcast issue.
Also it looks like ckio is doing bcasts to ckDestroy right now.

**Pull request merged**
