### PR TITLE
Fix projections logs for CREATION_{BCAST, MULTICAST} broken in e77ede

### PR DESCRIPTION
**Pull request by rbuch**
e77edeca133aa0c7584a6b89d555cf408abc6887 removed the number of PEs from the `LogEntry::pup` function, which Projections needs to read the logs.

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Spurious UCX failure:

```
2020-07-22T01:14:38.9610217Z make -C varTRAM test OPTS='-g -optimize -production' TESTOPTS=''
2020-07-22T01:14:38.9632265Z make[2]: Entering directory '/home/runner/work/charm/charm/ucx-linux-x86_64-ompipmix/tests/charm++/varTRAM'
2020-07-22T01:14:38.9632721Z ../../../bin/charmc -g -optimize -production  vartest.ci
2020-07-22T01:14:39.0117270Z ../../../bin/charmc -g -optimize -production  -c vartest.C
2020-07-22T01:14:45.0726908Z ../../../bin/charmc -g -optimize -production  -language charm++ -o vartest vartest.o
2020-07-22T01:14:45.8841621Z ../../../bin/testrun  ./vartest +p4 8 100 100 
2020-07-22T01:14:45.8955152Z 
2020-07-22T01:14:45.8955860Z Running on 4 processors:  ./vartest 8 100 100 
2020-07-22T01:14:45.9021639Z charmrun>  /usr/bin/setarch x86_64 -R  mpirun -np 4  ./vartest 8 100 100 
2020-07-22T01:14:45.9608653Z Charm++> Running in non-SMP mode: 4 processes (PEs)
2020-07-22T01:14:45.9609414Z Converse/Charm++ Commit ID: v6.11.0-devel-319-g559c320f1
2020-07-22T01:14:45.9845697Z Isomalloc> Synchronized global address space.
2020-07-22T01:14:45.9848695Z CharmLB> Load balancer assumes all CPUs are same.
2020-07-22T01:14:46.0544132Z Charm++> Running on 1 hosts (1 sockets x 2 cores x 1 PUs = 2-way SMP)
2020-07-22T01:14:46.0764662Z Charm++> cpu topology info is gathered in 0.091 seconds.
2020-07-22T01:14:46.1765917Z Time : 99737707 us
2020-07-22T01:51:40.8566113Z ##[error]The operation was canceled.
```

**Comment by matthiasdiener** [comment]
> Out of curiosity, is there any test in charm++ that exposes this issue? 

See also #2978.

**Comment by rbuch** [comment]
> Out of curiosity, is there any test in charm++ that exposes this issue?

No, but one should be added. It should run build Charm++ with tracing, run an example program to generate traces, and then run Projections and try ingesting them. It'll require some doing because Projections will catch a lot of errors internally (this one, for example, was caught internally and just showed up as an empty PE in Timeline).

**Comment by matthiasdiener** [comment]
> > Out of curiosity, is there any test in charm++ that exposes this issue?
> 
> No, but one should be added. It should run build Charm++ with tracing, run an example program to generate traces, and then run Projections and try ingesting them.

We do something like that in Github CI currently (see https://github.com/UIUC-PPL/charm/blob/master/.github/workflows/multicore_darwin.yml) 

> It'll require some doing because Projections will catch a lot of errors internally (this one, for example, was caught internally and just showed up as an empty PE in Timeline).

Ok, this explains why the CI test (and #2978) didn't catch it.

**Pull request merged**
