### PR TITLE
Bug #2647: Revert use of logical CPU indices in cpuAffinityRecvHandler

### PR DESCRIPTION
**Pull request by evan-charmworks**
PR #2448 caused a performance regression for existing users of
+setcpuaffinity and redefined the meaning of values passed to the
+excludecore parameter.

On machines such as Bridges where +setcpuaffinity crashes after this
reversion (#2445), try also passing +excludecore 0.

### CODE REVIEW

**Comment by evan-charmworks** [comment]
@nitbhat, does this PR show the problem originally fixed in #2445, and if so, does passing `+excludecore 0` work around it?

**Comment by stwhite91** [comment]
@nitbhat have you been able to look at this?

**Comment by nitbhat** [comment]
@evan-charmworks @SamTWhite: On Bridges (Both MPI-SMP and OFI-SMP) crash when run with `+setcpuaffinity` and `+setcpuaffinity +excludecore 0`.

**Comment by nitbhat** [comment]
```
[nbhat4@r005 megatest]$ make test TESTOPTS="+excludecore 0 +setcpuaffinity"
../../../bin/testrun  ./pgm +p1  +excludecore 0 +setcpuaffinity

Running on 1 processors:  ./pgm +excludecore 0 +setcpuaffinity
charmrun>  /usr/bin/setarch x86_64 -R  mpirun -np 1  ./pgm +excludecore 0 +setcpuaffinity
Charm++>ofi> provider: psm2
Charm++>ofi> control progress: 2
Charm++>ofi> data progress: 2
Charm++>ofi> maximum inject message size: 64
Charm++>ofi> eager maximum message size: 65536 (maximum header size: 40)
Charm++>ofi> cq entries count: 8
Charm++>ofi> use inject: 1
Charm++>ofi> maximum rma size: 4294967295
Charm++>ofi> mr mode: 0x1
Charm++>ofi> use memory pool: 0
Charm++>ofi> use request cache: 0
Charm++>ofi> number of pre-allocated recvs: 8
Charm++>ofi> exchanging addresses over OFI
Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.10.0-rc2-70-g9e8e3af
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled.
Charm++> cpuaffinity excludes core: 0.
[0] Stack Traceback:
  [0:0] pgm 0x80b8d3 CmiAbortHelper(char const*, char const*, char const*, int, int)
  [0:1] pgm 0x80b9ab CmiGetNonLocal
  [0:2] pgm 0x83124a
  [0:3] pgm 0x8157cf CmiHandleMessage
  [0:4] pgm 0x815e66 CmiDeliverSpecificMsg
  [0:5] pgm 0x83250a CmiInitCPUAffinity
  [0:6] pgm 0x6fd09f _initCharm(int, char**)
  [0:7] pgm 0x80b617
  [0:8] pgm 0x80b21a ConverseInit
  [0:9] pgm 0x6fdbaa charm_main
  [0:10] pgm 0x6f4385 main
  [0:11] libc.so.6 0x7ff87e9a3495 __libc_start_main
  [0:12] pgm 0x655e99
Error: CmiSetCPUAffinity failed to bind PE #0 to PU #1.
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: CmiSetCPUAffinity failed!

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 11179 RUNNING AT r005
=   EXIT STATUS: 1
===================================================================================

real	0m0.239s
user	0m0.042s
sys	0m0.088s
make: *** [test] Error 1
```

**Comment by evan-charmworks** [comment]
> On Bridges (Both MPI-SMP and OFI-SMP) crash when run with `+setcpuaffinity` and `+setcpuaffinity +excludecore 0`.

Thanks for testing that. Maybe it's possible that there is a set of options that will allow this to work on Bridges, such as `+setcpuaffinity +excludecore 0 +excludecore 1`, etc. I don't want to turn this into a wild goose chase though. It's looking like this doesn't have a straightforward solution.

**Comment by minitu** [comment]
lstopo-no-graphics output from RM node of Bridges:

```
jchoi157@r263:1darray$ lstopo-no-graphics 
Machine (128GB total)
  Package L#0
    NUMANode L#0 (P#0 64GB)
    L3 L#0 (35MB)
      L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
      L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
      L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
      L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
      L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4 + PU L#4 (P#4)
      L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5 + PU L#5 (P#5)
      L2 L#6 (256KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6 + PU L#6 (P#6)
      L2 L#7 (256KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7 + PU L#7 (P#14)
      L2 L#8 (256KB) + L1d L#8 (32KB) + L1i L#8 (32KB) + Core L#8 + PU L#8 (P#15)
      L2 L#9 (256KB) + L1d L#9 (32KB) + L1i L#9 (32KB) + Core L#9 + PU L#9 (P#16)
      L2 L#10 (256KB) + L1d L#10 (32KB) + L1i L#10 (32KB) + Core L#10 + PU L#10 (P#17)
      L2 L#11 (256KB) + L1d L#11 (32KB) + L1i L#11 (32KB) + Core L#11 + PU L#11 (P#18)
      L2 L#12 (256KB) + L1d L#12 (32KB) + L1i L#12 (32KB) + Core L#12 + PU L#12 (P#19)
      L2 L#13 (256KB) + L1d L#13 (32KB) + L1i L#13 (32KB) + Core L#13 + PU L#13 (P#20)
    HostBridge
      PCIBridge
        PCI 03:00.0 (Fabric)
          Net "ib0"
          OpenFabrics "hfi1_0"
      PCIBridge
        PCI 01:00.1 (VGA)
      PCIBridge
        PCI 02:00.0 (Ethernet)
          Net "eno1"
        PCI 02:00.1 (Ethernet)
          Net "eno2"
      PCI 00:1f.2 (SATA)
        Block(Disk) "sda"
        Block(Disk) "sdb"
  Package L#1
    NUMANode L#1 (P#1 64GB)
    L3 L#1 (35MB)
      L2 L#14 (256KB) + L1d L#14 (32KB) + L1i L#14 (32KB) + Core L#14 + PU L#14 (P#7)
      L2 L#15 (256KB) + L1d L#15 (32KB) + L1i L#15 (32KB) + Core L#15 + PU L#15 (P#8)
      L2 L#16 (256KB) + L1d L#16 (32KB) + L1i L#16 (32KB) + Core L#16 + PU L#16 (P#9)
      L2 L#17 (256KB) + L1d L#17 (32KB) + L1i L#17 (32KB) + Core L#17 + PU L#17 (P#10)
      L2 L#18 (256KB) + L1d L#18 (32KB) + L1i L#18 (32KB) + Core L#18 + PU L#18 (P#11)
      L2 L#19 (256KB) + L1d L#19 (32KB) + L1i L#19 (32KB) + Core L#19 + PU L#19 (P#12)
      L2 L#20 (256KB) + L1d L#20 (32KB) + L1i L#20 (32KB) + Core L#20 + PU L#20 (P#13)
      L2 L#21 (256KB) + L1d L#21 (32KB) + L1i L#21 (32KB) + Core L#21 + PU L#21 (P#21)
      L2 L#22 (256KB) + L1d L#22 (32KB) + L1i L#22 (32KB) + Core L#22 + PU L#22 (P#22)
      L2 L#23 (256KB) + L1d L#23 (32KB) + L1i L#23 (32KB) + Core L#23 + PU L#23 (P#23)
      L2 L#24 (256KB) + L1d L#24 (32KB) + L1i L#24 (32KB) + Core L#24 + PU L#24 (P#24)
      L2 L#25 (256KB) + L1d L#25 (32KB) + L1i L#25 (32KB) + Core L#25 + PU L#25 (P#25)
      L2 L#26 (256KB) + L1d L#26 (32KB) + L1i L#26 (32KB) + Core L#26 + PU L#26 (P#26)
      L2 L#27 (256KB) + L1d L#27 (32KB) + L1i L#27 (32KB) + Core L#27 + PU L#27 (P#27)
```

**Comment by minitu** [comment]
Tested using OFI SMP build with command `./build charm++ ofi-linux-x86_64 smp -j --with-production`, and 1darray hello example (examples/charm++/hello/1darray).
Seems like `+setcpuaffinity` and `+excludecore` work fine with this PR on Bridges:

```
jchoi157@r263:1darray$ mpirun -np 1 ./hello +ppn 1 +setcpuaffinity +showcpuaffinity
Charm++>ofi> provider: psm2
Charm++>ofi> control progress: 2
Charm++>ofi> data progress: 2
Charm++>ofi> maximum inject message size: 64
Charm++>ofi> eager maximum message size: 65536 (maximum header size: 40)
Charm++>ofi> cq entries count: 8
Charm++>ofi> use inject: 1
Charm++>ofi> maximum rma size: 4294967295
Charm++>ofi> mr mode: 0x1
Charm++>ofi> use memory pool: 0
Charm++>ofi> use request cache: 0
Charm++>ofi> number of pre-allocated recvs: 8
Charm++>ofi> exchanging addresses over OFI
Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.10.0-rc2-84-geb95ff2
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled.
[1] thread CPU affinity mask is 0x00000001
[0] thread CPU affinity mask is 0x00000001
Charm++> Running on 1 hosts (2 sockets x 14 cores x 1 PUs = 28-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
Running Hello on 1 processors for 5 elements
Hello 0 created
Hello 1 created
Hello 2 created
Hello 3 created
Hello 4 created
Main::initDone reached
Hi[17] from element 0
Hi[18] from element 1
Hi[19] from element 2
Hi[20] from element 3
Hi[21] from element 4
All done
[Partition 0][Node 0] End of program
```

```
jchoi157@r263:1darray$ mpirun -np 1 ./hello +ppn 1 +setcpuaffinity +excludecore 0 +showcpuaffinity
Charm++>ofi> provider: psm2
Charm++>ofi> control progress: 2
Charm++>ofi> data progress: 2
Charm++>ofi> maximum inject message size: 64
Charm++>ofi> eager maximum message size: 65536 (maximum header size: 40)
Charm++>ofi> cq entries count: 8
Charm++>ofi> use inject: 1
Charm++>ofi> maximum rma size: 4294967295
Charm++>ofi> mr mode: 0x1
Charm++>ofi> use memory pool: 0
Charm++>ofi> use request cache: 0
Charm++>ofi> number of pre-allocated recvs: 8
Charm++>ofi> exchanging addresses over OFI
Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.10.0-rc2-84-geb95ff2
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity excludes core: 0.
[0] thread CPU affinity mask is 0x00000002
[1] thread CPU affinity mask is 0x00000001
Charm++> Running on 1 hosts (2 sockets x 14 cores x 1 PUs = 28-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
Running Hello on 1 processors for 5 elements
Hello 0 created
Hello 1 created
Hello 2 created
Hello 3 created
Hello 4 created
Main::initDone reached
Hi[17] from element 0
Hi[18] from element 1
Hi[19] from element 2
Hi[20] from element 3
Hi[21] from element 4
All done
[Partition 0][Node 0] End of program
```

Even with multiple PPN:
```
jchoi157@r263:1darray$ mpirun -np 1 ./hello +ppn 4 +setcpuaffinity +excludecore 0 +showcpuaffinity
Charm++>ofi> provider: psm2
Charm++>ofi> control progress: 2
Charm++>ofi> data progress: 2
Charm++>ofi> maximum inject message size: 64
Charm++>ofi> eager maximum message size: 65536 (maximum header size: 40)
Charm++>ofi> cq entries count: 8
Charm++>ofi> use inject: 1
Charm++>ofi> maximum rma size: 4294967295
Charm++>ofi> mr mode: 0x1
Charm++>ofi> use memory pool: 0
Charm++>ofi> use request cache: 0
Charm++>ofi> number of pre-allocated recvs: 8
Charm++>ofi> exchanging addresses over OFI
Charm++> Running in SMP mode: 1 processes, 4 worker threads (PEs) + 1 comm threads per process, 4 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.10.0-rc2-84-geb95ff2
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> cpuaffinity excludes core: 0.
[0] thread CPU affinity mask is 0x00000002
[2] thread CPU affinity mask is 0x00000008
[1] thread CPU affinity mask is 0x00000004
[4] thread CPU affinity mask is 0x00000001
[3] thread CPU affinity mask is 0x00000010
Charm++> Running on 1 hosts (2 sockets x 14 cores x 1 PUs = 28-way SMP)
Charm++> cpu topology info is gathered in 0.001 seconds.
Running Hello on 4 processors for 5 elements
Hello 0 created
Hello 1 created
Hello 2 created
Hello 4 created
Hello 3 created
Main::initDone reached
Hi[17] from element 0
Hi[18] from element 1
Hi[19] from element 2
Hi[20] from element 3
Hi[21] from element 4
All done
[Partition 0][Node 0] End of program
```

Will test to with an infinite while loop and `top` to see if the mapping is performed correctly.

**Comment by minitu** [comment]
Verified with `top` that the mapping is indeed performed correctly. One thing I noticed with `+setcpuaffinity` is that the comm thread is always mapped to PE 0 and shares it with a worker thread unless `+excludecore 0` is used, I assume this is expected behavior?

**Comment by evan-charmworks** [comment]
> One thing I noticed with `+setcpuaffinity` is that the comm thread is always mapped to PU 0 and shares it with a worker thread unless `+excludecore 0` is used, I assume this is expected behavior?

Yes, this is known behavior. CmiInitCPUAffinity and CmiInitCPUTopology are only called after Converse has passed execution to the user's program, which means that the comm thread does not execute them.

**Comment by evan-charmworks** [comment]
Superseded by #2664

**Pull request closed without merging**
