### PR TITLE
Mempool: Generalize mempool to allow multiple different instantiations

### PR DESCRIPTION
**Pull request by evan-charmworks**
*Original date: 2018-06-04 18:35:24*
*Original PR: https://charm.cs.illinois.edu/gerrit/2306*

---

Change-Id: Iadb1d40fd59fd09d8146f9abb51dafe439c98f69

### CODE REVIEW

**Comment by mprobson** [comment]
Adding back reviewers from original PR, omitting graduated students:
- Phil Miller

**Comment by evan-charmworks** [comment]
I have concerns regarding any expansion in use of the GNI mempool. I have found it to be bug-prone and hard to understand. For any new mempool use cases I would recommend an individualized discussion of their pooling needs and the addition of a permissively-licensed off-the-shelf mempool or the creation or adaptation of an existing one, such as the Isomempool.

**Comment by mprobson** [comment]
I agree, I was just trying to realign this old issue with it's status on Gerrit by adding back reviewers. Maybe this is something we should discuss in core tomorrow?

**Comment by evan-charmworks** [comment]
@minitu You aren't using the GNI mempool in your work, are you? If not we can probably close this.

**Comment by minitu** [comment]
@evan-charmworks No I'm not, closing this.

**Pull request closed without merging**
