### PR TITLE
AMPI: Link ROMIO with libpthread

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Could you comment on what this fixes? I think `-pthread` is generally better.

**Comment by evan-charmworks** [comment]
Updated

**Comment by evan-charmworks** [comment]
This fixes the following problem, a build time showstopper for any program that calls into ROMIO:

```
/usr/bin/ld: /home/evan/charm/netlrts-linux-x86_64/bin/../lib/libampiromio.a(onesided_aggregation.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by matthiasdiener** [comment]
> This fixes the following problem, a build time showstopper for any program that calls into ROMIO:
> 
> ```
> /usr/bin/ld: /home/evan/charm/netlrts-linux-x86_64/bin/../lib/libampiromio.a(onesided_aggregation.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
> //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> ```

This file (and a few others in ROMIO) will create internal pthreads. Not sure that would work at all. We can merge this patch to get around the build failure.

**Pull request merged**
