### PR TITLE
Move Windows CI from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by evan-charmworks** [comment]
NetLRTS-Windows tests ran extremely slow. Switched to Multicore.

**Comment by evan-charmworks** [comment]
Tests ran with acceptable speed up until the checkpoint test hung.

```

2020-12-16T01:28:17.6722742Z make[2]: Entering directory '/d/a/charm/charm/multicore-win-x86_64/tests/charm++/chkpt'
2020-12-16T01:28:17.6723262Z rm -rf log/
2020-12-16T01:28:17.6840705Z rm -fr log
2020-12-16T01:28:17.6983269Z ../../../bin/testrun  ./hello +p4  +setcpuaffinity
2020-12-16T01:28:17.7776031Z Running command:  ./hello  +p4 +setcpuaffinity
2020-12-16T01:28:17.7776664Z 
2020-12-16T01:28:20.9835333Z Charm++: standalone mode (not using charmrun)
2020-12-16T01:28:20.9836306Z Charm++> Running in Multicore mode: 4 threads (PEs)
2020-12-16T01:28:20.9837067Z Converse/Charm++ Commit ID: 3cb86ec
2020-12-16T01:28:20.9837833Z CharmLB> Load balancer assumes all CPUs are same.
2020-12-16T01:28:20.9838569Z Charm++> cpu affinity enabled. 
2020-12-16T01:28:20.9839915Z Charm++> Running on 1 hosts (1 sockets x 2 cores x 1 PUs = 2-way SMP)
2020-12-16T01:28:20.9841079Z Charm++> cpu topology info is gathered in 0.000 seconds.
2020-12-16T01:28:20.9842324Z Running Hello on 4 processors for 8 elements
2020-12-16T01:28:20.9842971Z step 0 done
2020-12-16T01:28:20.9844729Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9845591Z step 1 done
2020-12-16T01:28:20.9846053Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9846524Z step 2 done
2020-12-16T01:28:20.9846977Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9847504Z [0] Checkpoint starting in log
2020-12-16T01:28:20.9848023Z step 3 done
2020-12-16T01:28:20.9848508Z Main's PUPer. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9849024Z CHello's PUPer. step=3.
2020-12-16T01:28:20.9849594Z Checkpoint to disk finished in 2.603000s, sending out the cb...
2020-12-16T01:28:20.9850516Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9850997Z step 4 done
2020-12-16T01:28:20.9851491Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9851979Z step 5 done
2020-12-16T01:28:20.9852443Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9852921Z step 6 done
2020-12-16T01:28:20.9853390Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9854019Z step 7 done
2020-12-16T01:28:20.9854472Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9854937Z step 8 done
2020-12-16T01:28:20.9855403Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
2020-12-16T01:28:20.9855857Z step 9 done
2020-12-16T01:28:20.9868057Z 
2020-12-16T01:28:20.9872359Z real	0m3.234s
2020-12-16T01:28:20.9883366Z sync
2020-12-16T01:28:20.9888611Z user	0m0.000s
2020-12-16T01:28:20.9889356Z sys	0m0.030s
2020-12-16T01:28:21.1171509Z ../../../bin/testrun  ./hello +p4 +restart log  +setcpuaffinity
2020-12-16T01:28:21.2006009Z Running command:  ./hello  +p4 +restart log +setcpuaffinity
2020-12-16T01:28:21.2007123Z 
2020-12-16T02:34:29.3868382Z Terminate batch job (Y/N)? 
2020-12-16T02:34:29.3878356Z ^C
2020-12-16T02:34:30.0118060Z ##[error]The operation was canceled.```

**Comment by matthiasdiener** [comment]
Does running with `++local` (for netlrts mostly) make the tests run faster?

**Comment by evan-charmworks** [comment]
> Does running with `++local` (for netlrts mostly) make the tests run faster?

On Windows, Charmrun won't work at all without that (or the Charm Daemon which I have never used).

**Comment by evan-charmworks** [comment]
The checkpoint restart test timed out again, this time with NetLRTS TCP. The test runs with +p4 and the machine only provides us `1 sockets x 2 cores x 1 PUs = 2-way SMP`, so maybe that is contributing to it.

**Comment by matthiasdiener** [comment]
> The checkpoint restart test timed out again, this time with NetLRTS TCP. The test runs with +p4 and the machine only provides us `1 sockets x 2 cores x 1 PUs = 2-way SMP`, so maybe that is contributing to it.

It's strange that this doesn't happen on the Travis CI, which should have the same number of cores.

**Comment by matthiasdiener** [comment]
Maybe try compiling Charm++/the tests without `-g`

**Comment by evan-charmworks** [comment]
`--without-romio` does not need to be specified. The build scripts apply it on Windows automatically.

`-j2` is preferable to `-j3` because `-j3` stalls the system enough that output is not regularly output to the CI output view page, while not actually helping the build go any faster.

**Comment by matthiasdiener** [comment]
> Tests ran with acceptable speed on multicore up until the checkpoint test timed out.
> 
> ```
> 
> 2020-12-16T01:28:17.6722742Z make[2]: Entering directory '/d/a/charm/charm/multicore-win-x86_64/tests/charm++/chkpt'
> 2020-12-16T01:28:17.6723262Z rm -rf log/
> 2020-12-16T01:28:17.6840705Z rm -fr log
> 2020-12-16T01:28:17.6983269Z ../../../bin/testrun  ./hello +p4  +setcpuaffinity
> 2020-12-16T01:28:17.7776031Z Running command:  ./hello  +p4 +setcpuaffinity
> 2020-12-16T01:28:17.7776664Z 
> 2020-12-16T01:28:20.9835333Z Charm++: standalone mode (not using charmrun)
> 2020-12-16T01:28:20.9836306Z Charm++> Running in Multicore mode: 4 threads (PEs)
> 2020-12-16T01:28:20.9837067Z Converse/Charm++ Commit ID: 3cb86ec
> 2020-12-16T01:28:20.9837833Z CharmLB> Load balancer assumes all CPUs are same.
> 2020-12-16T01:28:20.9838569Z Charm++> cpu affinity enabled. 
> 2020-12-16T01:28:20.9839915Z Charm++> Running on 1 hosts (1 sockets x 2 cores x 1 PUs = 2-way SMP)
> 2020-12-16T01:28:20.9841079Z Charm++> cpu topology info is gathered in 0.000 seconds.
> 2020-12-16T01:28:20.9842324Z Running Hello on 4 processors for 8 elements
> 2020-12-16T01:28:20.9842971Z step 0 done
> 2020-12-16T01:28:20.9844729Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9845591Z step 1 done
> 2020-12-16T01:28:20.9846053Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9846524Z step 2 done
> 2020-12-16T01:28:20.9846977Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9847504Z [0] Checkpoint starting in log
> 2020-12-16T01:28:20.9848023Z step 3 done
> 2020-12-16T01:28:20.9848508Z Main's PUPer. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9849024Z CHello's PUPer. step=3.
> 2020-12-16T01:28:20.9849594Z Checkpoint to disk finished in 2.603000s, sending out the cb...
> 2020-12-16T01:28:20.9850516Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9850997Z step 4 done
> 2020-12-16T01:28:20.9851491Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9851979Z step 5 done
> 2020-12-16T01:28:20.9852443Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9852921Z step 6 done
> 2020-12-16T01:28:20.9853390Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9854019Z step 7 done
> 2020-12-16T01:28:20.9854472Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9854937Z step 8 done
> 2020-12-16T01:28:20.9855403Z myClient. a=123(0000000000C4C294), b[0]=456(0000000000C4C298), b[1]=789
> 2020-12-16T01:28:20.9855857Z step 9 done
> 2020-12-16T01:28:20.9868057Z 
> 2020-12-16T01:28:20.9872359Z real	0m3.234s
> 2020-12-16T01:28:20.9883366Z sync
> 2020-12-16T01:28:20.9888611Z user	0m0.000s
> 2020-12-16T01:28:20.9889356Z sys	0m0.030s
> 2020-12-16T01:28:21.1171509Z ../../../bin/testrun  ./hello +p4 +restart log  +setcpuaffinity
> 2020-12-16T01:28:21.2006009Z Running command:  ./hello  +p4 +restart log +setcpuaffinity
> 2020-12-16T01:28:21.2007123Z 
> 2020-12-16T02:34:29.3868382Z Terminate batch job (Y/N)? 
> 2020-12-16T02:34:29.3878356Z ^C
> 2020-12-16T02:34:30.0118060Z ##[error]The operation was canceled.```
> ```

I misunderstood this - it is not the chkpt test timing out, it is just hitting the 90 minutes CI time limit that we configured.

**Comment by evan-charmworks** [comment]
> I misunderstood this - it is not the chkpt test timing out, it is just hitting the 90 minutes CI time limit that we configured.

No, it is the chkpt test timing out. Look at the gap in timestamps between these lines:

```
2020-12-16T01:28:21.1171509Z ../../../bin/testrun  ./hello +p4 +restart log  +setcpuaffinity
2020-12-16T01:28:21.2006009Z Running command:  ./hello  +p4 +restart log +setcpuaffinity
2020-12-16T01:28:21.2007123Z 
2020-12-16T02:34:29.3868382Z Terminate batch job (Y/N)? 
```

By removing `-g` you managed to avoid this hang. However the NetLRTS build was still timing out due to the slowness I mentioned. I believe this is due to our ethernet code being inefficient, making multiple write syscalls in sequence instead of batching them into one.

**Comment by evan-charmworks** [comment]
I don't think we should use a CI configuration that takes up to three hours to complete. We can let this build run to see if it eventually succeeds but after that I'm thinking we should change it back to multicore.

**Comment by evan-charmworks** [comment]
Great! I guess `+setcpuaffinity` hurt performance instead of helping.

**Review by matthiasdiener — APPROVED** [review]

**Review by minitu — APPROVED** [review]

**Pull request merged**
