### PR TITLE
Change license to Apache-2.0 with LLVM exceptions

### PR DESCRIPTION
**Pull request by matthiasdiener**
(per our email discussion)

Same could be done for charm4py, projections, ...

### CODE REVIEW

**Review by ericjbohm — APPROVED** [review]

**Review by bhatele — APPROVED** [review]

**Review by PhilMiller — APPROVED** [review]
Not that you need my approval, but I'm glad to see this finally come out!

**Comment by matthiasdiener** [comment]
Next step:

add a `NOTICE` file (similar to https://github.com/spack/spack/blob/develop/NOTICE) with the following information:
  - acknowledging UIUC, and Charmworks, and multiple grants (not individually listed)  from NSF, NIH, DoE that directly or indirectly supported this work.

**Comment by lvkale** [comment]
When we change this, we should also change the license in the readthedocs (or remove it from there)
https://charm.readthedocs.io/en/latest/license.html

**Comment by ericjbohm** [comment]
Changed to target Charm-8.0.0, which will just be Charm-7.0.0 with the license and related doc changes.

**Comment by matthiasdiener** [comment]
> When we change this, we should also change the license in the readthedocs (or remove it from there) https://charm.readthedocs.io/en/latest/license.html

That license is just `#included` from the main `LICENSE` file, so a change there will automatically be reflected on readthedocs.

**Comment by ericjbohm** [comment]
> Next step:
> 
> add a `NOTICE` file (similar to https://github.com/spack/spack/blob/develop/NOTICE) with the following information:
> 
> * acknowledging UIUC, and Charmworks, and multiple grants (not individually listed)  from NSF, NIH, DoE that directly or indirectly supported this work.

Draft of NOTICE file added to this PR.

**Review by bhatele — APPROVED** [review]

**Pull request merged**
