### PR TITLE
Converse randomTTL and kNeighbors benchmarks 

### PR DESCRIPTION
**Pull request by nitbhat**

### CODE REVIEW

**Comment by nitbhat** [comment]
@minitu You had mentioned previously that you saw hangs for kNeighbor in the SMP mode (on Summit). Could you share your run details?

**Comment by minitu** [comment]
@nitbhat I only observe the hang with the PAMILRTS layer, with MPI layer it runs fine. The commands are:

**Comment by minitu** [comment]
Something else that's strange is that the startup time (before first output of the program appears) with PAMILRTS is much longer than the MPI layer. The hang also occurs maybe 1 out of 10 times.

**Comment by minitu** [comment]
Just tested the UCX layer and it works fine, similar to the MPI layer.

**Comment by nitbhat** [comment]
> Something else that's strange is that the startup time (before first output of the program appears) with PAMILRTS is much longer than the MPI layer. The hang also occurs maybe 1 out of 10 times.

Thanks @minitu. 
That's strange. It might be a weird messaging race condition that probably rarely gets triggered with PAMILRTS.

**Comment by minitu** [comment]
Just fixed segfault due to missing `CpvInitialize` in `randomttl` as well.

Testing `randomttl` with the same configurations as `kneighbors`, MPI and UCX layers work without any issues.
But PAMILRTS has the same slowdown and occasional hang issue.

Commands are as follows:
MPI & UCX: `jsrun -n4 -a1 -c20 -K1 -r2 ./randomttl 50 1000 +ppn 19 +pemap L4-76:4,84-156:4 +commap L0,80`
PAMILRTS: `jsrun -n4 -a1 -c20 -K1 -r2 ./randomttl 50 1000 +ppn 20 +pemap L0-76:4,80-156:4`

**Pull request merged**
