### PR TITLE
AMPI: increase objid collection bits for AMPI-only builds

### PR DESCRIPTION
**Pull request by stwhite91**
This leaves 32 bits for the element id, 29 for the collection id, and 3 for the tag bits.

### CODE REVIEW

**Comment by evan-charmworks** [comment]
UCX failure appears spurious:

```
2020-03-11T15:23:27.7089464Z ../../../../../../bin/testrun  +p4 ./simpleZeroCopy 32 +balancer GreedyLB 
2020-03-11T15:23:27.7236422Z 
2020-03-11T15:23:27.7237103Z Running on 4 processors:  ./simpleZeroCopy 32 +balancer GreedyLB 
2020-03-11T15:23:27.7373418Z charmrun>  /usr/bin/setarch x86_64 -R  mpirun -np 4  ./simpleZeroCopy 32 +balancer GreedyLB 
2020-03-11T15:23:27.8076073Z Charm++> Running in non-SMP mode: 4 processes (PEs)
2020-03-11T15:23:27.8076547Z Converse/Charm++ Commit ID: v6.10.0-rc2-169-gd3ee46c1e
2020-03-11T15:23:27.8222326Z Isomalloc> Synchronized global address space.
2020-03-11T15:23:27.8226712Z CharmLB> Load balancer assumes all CPUs are same.
2020-03-11T15:23:27.8421436Z Charm++> Running on 1 hosts (1 sockets x 2 cores x 1 PUs = 2-way SMP)
2020-03-11T15:23:27.8541477Z Charm++> cpu topology info is gathered in 0.030 seconds.
2020-03-11T15:23:27.8549940Z CharmLB> GreedyLB created.
2020-03-11T15:23:27.8582081Z send: completed
2020-03-11T15:23:27.8593218Z zerocopySend: completed
2020-03-11T15:23:27.9062422Z mixedSend: completed
2020-03-11T15:23:27.9263670Z sdagRun: Iteration 2 completed
2020-03-11T15:23:27.9278145Z sdagRun: Iteration 3 completed
2020-03-11T15:23:27.9467928Z sdagRun: Iteration 4 completed
2020-03-11T15:23:28.5103841Z sdagRun: Iteration 5 completed
2020-03-11T15:23:28.5582914Z sdagRun: Iteration 6 completed
2020-03-11T15:23:28.6221010Z sdagRun: Iteration 7 completed
2020-03-11T15:23:28.6861134Z sdagRun: Iteration 8 completed
2020-03-11T15:23:28.7513958Z sdagRun: Iteration 9 completed
2020-03-11T15:23:28.9982832Z sdagRun: Iteration 10 completed
2020-03-11T15:23:28.9985541Z sdagRun: Iteration 11 completed
2020-03-11T15:23:28.9987804Z sdagRun: Iteration 12 completed
2020-03-11T15:23:29.0381405Z sdagRun: Iteration 13 completed
2020-03-11T15:23:29.0385380Z sdagRun: Iteration 14 completed
2020-03-11T15:23:29.5861260Z sdagRun: Iteration 15 completed
2020-03-11T15:23:29.5864085Z sdagRun: Iteration 16 completed
2020-03-11T15:23:29.5890098Z sdagRun: Iteration 17 completed
2020-03-11T15:23:29.6427662Z sdagRun: Iteration 18 completed
2020-03-11T15:23:29.6646525Z sdagRun: Iteration 19 completed
2020-03-11T15:23:30.1142416Z sdagRun: Iteration 20 completed
2020-03-11T15:23:30.1301593Z sdagRun: Iteration 21 completed
2020-03-11T15:23:30.1304102Z sdagRun: Iteration 22 completed
2020-03-11T15:23:30.1306670Z sdagRun: Iteration 23 completed
2020-03-11T15:23:30.1309654Z sdagRun: Iteration 24 completed
2020-03-11T15:23:30.6545657Z sdagRun: Iteration 25 completed
2020-03-11T15:23:30.6547086Z sdagRun: Iteration 26 completed
2020-03-11T15:23:30.6549037Z sdagRun: Iteration 27 completed
2020-03-11T15:23:30.6551177Z sdagRun: Iteration 28 completed
2020-03-11T15:23:30.6553113Z sdagRun: Iteration 29 completed
2020-03-11T15:23:31.2184765Z sdagRun: Iteration 30 completed
2020-03-11T15:23:31.2188077Z sdagRun: Iteration 31 completed
2020-03-11T15:23:31.2190968Z sdagRun: Iteration 32 completed
2020-03-11T15:23:31.2194140Z sdagRun: Iteration 33 completed
2020-03-11T15:23:31.2196765Z sdagRun: Iteration 34 completed
2020-03-11T15:23:31.7546692Z sdagRun: Iteration 35 completed
2020-03-11T15:23:31.7550072Z sdagRun: Iteration 36 completed
2020-03-11T15:23:31.7552508Z sdagRun: Iteration 37 completed
2020-03-11T15:23:31.7554858Z sdagRun: Iteration 38 completed
2020-03-11T15:23:31.7557204Z sdagRun: Iteration 39 completed
2020-03-11T15:23:32.3701824Z sdagRun: Iteration 40 completed
2020-03-11T15:23:32.3901602Z [fv-az89:79895:0:79895] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
2020-03-11T15:23:32.3915947Z ==== backtrace (tid:  79895) ====
2020-03-11T15:23:32.3979817Z  0  /usr/lib/libucs.so.0(ucs_handle_error+0x124) [0x7ffff7954a44]
2020-03-11T15:23:32.3980915Z  1  /usr/lib/libucs.so.0(+0x23e6c) [0x7ffff7954e6c]
2020-03-11T15:23:32.3981964Z  2  /usr/lib/libucs.so.0(+0x240e4) [0x7ffff79550e4]
2020-03-11T15:23:32.3983449Z  3  /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7ffff619df20]
2020-03-11T15:23:32.3984547Z  4  /usr/lib/libucp.so.0(ucp_tag_send_nb+0x1d) [0x7ffff7bacf8d]
2020-03-11T15:23:32.3985597Z  5  ./simpleZeroCopy(_Z12LrtsSendFunciiiPci+0x3a) [0x55555571812a]
2020-03-11T15:23:32.3986654Z  6  ./simpleZeroCopy(CldEnqueue+0xfe) [0x55555577da8e]
2020-03-11T15:23:32.3987697Z  7  ./simpleZeroCopy(_ZNK10CkCallback4sendEPv+0x56d) [0x55555565badd]
2020-03-11T15:23:32.3988744Z  8  ./simpleZeroCopy(_ZN14CkReductionMgr15finishReductionEv+0x3ae) [0x5555556ab28e]
2020-03-11T15:23:32.3989804Z  9  ./simpleZeroCopy(_ZN14CkReductionMgr7RecvMsgEP14CkReductionMsg+0x81) [0x5555556abb11]
2020-03-11T15:23:32.3990853Z 10  ./simpleZeroCopy(CkDeliverMessageFree+0x2a) [0x5555556474ba]
2020-03-11T15:23:32.3991880Z 11  ./simpleZeroCopy(_Z15_processHandlerPvP11CkCoreState+0x182b) [0x55555565073b]
2020-03-11T15:23:32.3992919Z 12  ./simpleZeroCopy(CsdScheduleForever+0xb7) [0x55555571b587]
2020-03-11T15:23:32.3993951Z 13  ./simpleZeroCopy(CsdScheduler+0x2d) [0x55555571b8ad]
2020-03-11T15:23:32.3994991Z 14  ./simpleZeroCopy(ConverseInit+0x56a) [0x55555571972a]
2020-03-11T15:23:32.3996019Z 15  ./simpleZeroCopy(charm_main+0x29) [0x55555563f3e9]
2020-03-11T15:23:32.3997326Z 16  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7ffff6180b97]
2020-03-11T15:23:32.3998712Z 17  ./simpleZeroCopy(_start+0x2a) [0x55555560e74a]
2020-03-11T15:23:32.3999766Z =================================
2020-03-11T15:23:32.6128021Z --------------------------------------------------------------------------
2020-03-11T15:23:32.6128638Z Primary job  terminated normally, but 1 process returned
2020-03-11T15:23:32.6129122Z a non-zero exit code. Per user-direction, the job has been aborted.
2020-03-11T15:23:32.6129613Z --------------------------------------------------------------------------
2020-03-11T15:23:33.6165206Z --------------------------------------------------------------------------
2020-03-11T15:23:33.6167274Z mpirun noticed that process rank 0 with PID 0 on node fv-az89 exited on signal 11 (Segmentation fault).
2020-03-11T15:23:33.6167762Z --------------------------------------------------------------------------
2020-03-11T15:23:33.6223654Z Makefile:18: recipe for target 'test' failed
2020-03-11T15:23:33.6224941Z 
2020-03-11T15:23:33.6225683Z make[6]: Leaving directory '/home/runner/work/charm/charm/ucx-linux-x86_64-ompipmix/examples/charm++/zerocopy/entry_method_post_api/reg/simpleZeroCopy'
```

**Comment by matthiasdiener** [comment]
> UCX failure appears spurious:

That error seems to happen quite often now, do we know what caused it?

**Comment by evan-charmworks** [comment]
Same failure again.

**Comment by stwhite91** [comment]
@nitbhat can you look into this failure in `examples/charm++/zerocopy/entry_method_post_api/reg/simpleZeroCopy/`?

**Pull request merged**
