### PR TITLE
Support: Warn not to use unoptimized build for benchmarking

### PR DESCRIPTION
**Pull request by rbuch**

### CODE REVIEW

**Comment by rbuch** [comment]
Adding the color codes may add some extra noise when output is redirected, but I think it's still worth it to make sure it's easily seen by users (and it still shows up when `cat`ing the file). We can also do it selectively be detecting if `stdout` is a tty or not, but making that fully portable isn't entirely trivial.

**Comment by matthiasdiener** [comment]
Imho, since we are not using color anywhere else in Charm++, it might not be necessary here either. How does this handle running with ++quiet?

**Comment by rbuch** [comment]
> Imho, since we are not using color anywhere else in Charm++, it might not be necessary here either. How does this handle running with ++quiet?

It doesn't get printed with `++quiet` (neither does the rest of the preamble).

I'm not married to the color idea, I just thought it'd be good to make it as evident as possible so that people would actually notice it.

**Comment by matthiasdiener** [comment]
> > Imho, since we are not using color anywhere else in Charm++, it might not be necessary here either. How does this handle running with ++quiet?
> 
> It doesn't get printed with `++quiet` (neither does the rest of the preamble).

Ok.

> I'm not married to the color idea, I just thought it'd be good to make it as evident as possible so that people would actually notice it.

Imho, we can't use color here. Not everyone uses white-on-black terminals, and depending on the color scheme the user has chosen that warning might be almost invisible. It is also not super portable (color in Windows terminals is weird, and we have seen issues in the cmake build where the color deactivation failed for some reason, which leads to *all* text printed in yellow).

I'd also argue that the warning is a bit too verbose, and would prefer just attaching `(debug build)` or `(production build)` to the end of the Charm++ version printed just before these warnings, but I'm happy to be overruled on that.

**Comment by rbuch** [comment]
> > > Imho, since we are not using color anywhere else in Charm++, it might not be necessary here either. How does this handle running with ++quiet?
> > 
> > 
> > It doesn't get printed with `++quiet` (neither does the rest of the preamble).
> 
> Ok.
> 
> > I'm not married to the color idea, I just thought it'd be good to make it as evident as possible so that people would actually notice it.
> 
> Imho, we can't use color here. Not everyone uses white-on-black terminals, and depending on the color scheme the user has chosen that warning might be almost invisible. It is also not super portable (color in Windows terminals is weird, and we have seen issues in the cmake build where the color deactivation failed for some reason, which leads to _all_ text printed in yellow).

That's a fair concern, I'll take the color stuff out.
 
> I'd also argue that the warning is a bit too verbose, and would prefer just attaching `(debug build)` or `(production build)` to the end of the Charm++ version printed just before these warnings, but I'm happy to be overruled on that.

I agree that the current warning is on the verbose side, I was coming from the position that if our concern was people using these builds for benchmarks, then we should be specific about telling them not to and giving them instructions on how to build to do so. That being said, perhaps just saying whether the build is a Debug or Release build is sufficient. I'm interested in hearing other opinions on this as well.

**Comment by minitu** [comment]
I think the outputs are still hard to catch, can we add some prefix like `WARNING:` to make it more visible?

**Comment by evan-charmworks** [comment]
@matthiasdiener It looks like CMake does not enable error checking by default like the old build system does.

**Comment by matthiasdiener** [comment]
> @matthiasdiener It looks like CMake does not enable error checking by default like the old build system does.

CC: #2839

**Pull request merged**
