### PR TITLE
cmake: add cmk_use_cma

### PR DESCRIPTION
**Pull request by matthiasdiener**

### CODE REVIEW

**Review by rbuch — DISMISSED** [review]

**Review by stwhite91 — DISMISSED** [review]

**Review by evan-charmworks — DISMISSED** [review]

**Comment by nitbhat** [comment]
On trying it on a lab machine with `./build LIBS mpi-linux-x86_64 --with-production --enable-error-checking --suffix=prod -j4`, I keep getting this warning: 
```
In file included from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/conv-config.h:63,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/conv-header.h:4,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/converse.h:62,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/charm.h:8,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/charm++.h:9,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/pose.decl.h:3,
                 from /scratch/nitin/charm_2/src/libs/ck-libs/pose/pose.h:9,
                 from /scratch/nitin/charm_2/src/libs/ck-libs/pose/gvt.C:2:
/scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/lrts-common.h:6: warning: "CMK_USE_CMA" redefined
 #define CMK_USE_CMA                    (CMK_HAS_CMA && !CMK_MULTICORE && !CMK_BLUEGENEQ)

In file included from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/conv-config.h:16,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/conv-header.h:4,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/converse.h:62,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/charm.h:8,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/charm++.h:9,
                 from /scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/pose.decl.h:3,
                 from /scratch/nitin/charm_2/src/libs/ck-libs/pose/pose.h:9,
                 from /scratch/nitin/charm_2/src/libs/ck-libs/pose/gvt.C:2:
/scratch/nitin/charm_2/mpi-linux-x86_64-prod/bin/../include/conv-autoconfig.h:176: note: this is the location of the previous definition
 #define CMK_USE_CMA 1
```

**Comment by evan-charmworks** [comment]
UTH:
```
/home/runner/work/charm/charm/uth-linux-x86_64/bin/../lib/libconv-core.a(conv-rdma.C.o): In function `CmiNcpyBuffer::cmaGet(CmiNcpyBuffer&)':
/home/runner/work/charm/charm/src/conv-core/conv-rdma.C:152: undefined reference to `CmiIssueRgetUsingCMA(void const*, void*, int, void const*, void*, int, unsigned long)'
/home/runner/work/charm/charm/uth-linux-x86_64/bin/../lib/libconv-core.a(conv-rdma.C.o): In function `CmiNcpyBuffer::cmaPut(CmiNcpyBuffer&)':
/home/runner/work/charm/charm/src/conv-core/conv-rdma.C:233: undefined reference to `CmiIssueRputUsingCMA(void const*, void*, int, void const*, void*, int, unsigned long)'
/home/runner/work/charm/charm/uth-linux-x86_64/bin/../lib/libconv-core.a(conv-rdma.C.o): In function `findTransferModeWithNodes(int, int)':
/home/runner/work/charm/charm/src/conv-core/conv-rdma.C:279: undefined reference to `CmiDoesCMAWork()'
collect2: error: ld returned 1 exit status
Fatal Error by charmc in directory /home/runner/work/charm/charm/uth-linux-x86_64
   Command g++ -rdynamic CMakeFiles/hello.dir/tests/charm++/simplearrayhello/hello.C.o moduleinit64678.o -L/home/runner/work/charm/charm/uth-linux-x86_64/bin/../lib -lckmain -lck -lmemory-default -lthreads-default -lconv-machine -lconv-core -ltmgr -lconv-util -lconv-partition -lhwloc_embedded -lm -lmemory-default -lthreads-default -lldb-rand -lconv-ldb -lckqt -lckqt -lz -ldl -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /home/runner/work/charm/charm/uth-linux-x86_64/bin/../lib/conv-static.o -o bin/hello returned error code 1
```

multicore darwin tracing is #2763

**Comment by matthiasdiener** [comment]
Ready for review.

**Review by evan-charmworks — APPROVED** [review]

**Review by nitbhat — APPROVED** [review]
Looks good, tested on a lab machine, and verified that it works correctly (i.e. tests run with `+noCMAForZC` for CMA enabled machines).

**Pull request merged**
