### PR TITLE
CI: Add ARM64 builds using CircleCI

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by evan-charmworks** [comment]
netlrts arm64 smp failure:

```
make -C megampi testp OPTS='-g -Werror=vla -optimize -production' TESTOPTS='++local +setcpuaffinity +CmiSleepOnIdle ++ppn 2' P='4'
make[3]: Entering directory '/home/circleci/project/netlrts-linux-arm8-smp/tests/ampi/megampi'
../../../bin/testrun   ./megampi +p4 +vp4  ++local +setcpuaffinity +CmiSleepOnIdle ++ppn 2
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 0.007 seconds.
Charm++> Running in SMP mode: 2 processes, 2 worker threads (PEs) + 1 comm threads per process, 4 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v7.1.0-devel-265-ge1e7c95f9
Charm++ built with internal error checking enabled.
Do not use for performance benchmarking (build without --enable-error-checking to do so).
Isomalloc> Synchronized global address space.
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> Running on 1 hosts (1 sockets x 2 cores x 1 PUs = 2-way SMP)
Charm++> cpu topology info is gathered in 0.069 seconds.
WARNING: Multiple PEs assigned to same core, recommend adjusting processor affinity or passing +CmiSleepOnIdle to reduce interference.
[0] No TreeLB configuration file found. Choosing a default configuration.
[0] TreeLB: Using PE_Process_Root tree with:
	Process: GreedyRefine 
	Root: GreedyRefine 
[0] Testing: Testing...
------------- Processor 1 Exiting: Called CmiAbort ------------
Reason: TCharm has not been initialized!

[1] Stack Traceback:
  [1:0] megampi 0xaaaaaae3674c 
  [1:1] megampi 0xaaaaaabc9f70 TCHARM_Migrate
  [1:2] megampi 0xaaaaaac5d12c AMPI_Migrate
  [1:3] megampi 0xaaaaaabc4390 MPI_Tester::testMigrate()
  [1:4] megampi 0xaaaaaabc4a98 AMPI_Main
  [1:5] megampi 0xaaaaaac323b8 AMPI_threadstart
  [1:6] megampi 0xaaaaaabc81dc 
  [1:7] megampi 0xaaaaaadd9024 CthStartThread(unsigned int, unsigned int, unsigned int, unsigned int)
  [1:8] libc.so.6 0xfffff7b6aba0 
Fatal error on PE 1> TCharm has not been initialized!


real	0m0.242s
user	0m0.004s
sys	0m0.000s
make[3]: *** [Makefile:26: testp] Error 1
make[3]: Leaving directory '/home/circleci/project/netlrts-linux-arm8-smp/tests/ampi/megampi
```

**Comment by evan-charmworks** [comment]
This failure is bizarre. I can reproduce it even on multicore, on a Jetson Orin Nano. I don't know why ARM platforms are so predisposed to it.

```
$ ./megampi +p2 +vp2 +LBDebug 1
Charm++: standalone mode (not using charmrun)
Charm++> Running in Multicore mode: 2 threads (PEs)
Converse/Charm++ Commit ID: v7.1.0-devel-297-gfe3889dfc
Charm++ built with internal error checking enabled.
Do not use for performance benchmarking (build without --enable-error-checking to do so).
Charm++> scheduler running in netpoll mode.
CharmLB> Verbose level 1, load balancing period: -1 seconds
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 6 cores x 1 PUs = 6-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
[0] No TreeLB configuration file found. Choosing a default configuration.
[0] TreeLB: Using PE_Root tree with: GreedyRefine
        Using 0 as root
        Test PE Speed: false
[0] Testing: Testing...
--------- Started LB step 0 ---------
[0] num_procs=2 num_objs=2
[0] obj loads: min=0.000985 mean=0.001392 max=0.001799
[0] proc loads: min=0.001581 mean=0.002062 max=0.002542
[0] GreedyRefine: greedy maxload is 0.002396, tolerance set to 1.000000
[0] strategy GreedyRefine time=0.000012 secs, maxLoad after strategy=0.002396, num_migrations=2 migrations_sum_hops=0
--------- Finished LB step 0 ---------
------------- Processor 1 Exiting: Called CmiAbort ------------
Reason: TCharm has not been initialized!

[0] lb time = 0.000275
[1] Stack Traceback:
  [1:0] megampi 0xaaaac251648c
  [1:1] megampi 0xaaaac22a9bd0 TCHARM_Migrate
  [1:2] megampi 0xaaaac233b5bc AMPI_Migrate
  [1:3] megampi 0xaaaac22a3fc0 MPI_Tester::testMigrate()
  [1:4] megampi 0xaaaac22a46c8 AMPI_Main
  [1:5] megampi 0xaaaac23113b0 AMPI_threadstart
  [1:6] megampi 0xaaaac22a7e24
  [1:7] megampi 0xaaaac24b91a4 CthStartThread(unsigned int, unsigned int, unsigned int, unsigned int)
  [1:8] libc.so.6 0xffffafed6ba0
Charm++ fatal error:
TCharm has not been initialized!

[1] Stack Traceback:
  [1:0] megampi 0xaaaac25162e8 LrtsAbort(char const*)
  [1:1] megampi 0xaaaac2516394 CmiAbortHelper(char const*, char const*, char const*, int, int)
  [1:2] megampi 0xaaaac251648c
  [1:3] megampi 0xaaaac22a9bd0 TCHARM_Migrate
  [1:4] megampi 0xaaaac233b5bc AMPI_Migrate
  [1:5] megampi 0xaaaac22a3fc0 MPI_Tester::testMigrate()
  [1:6] megampi 0xaaaac22a46c8 AMPI_Main
  [1:7] megampi 0xaaaac23113b0 AMPI_threadstart
  [1:8] megampi 0xaaaac22a7e24
  [1:9] megampi 0xaaaac24b91a4 CthStartThread(unsigned int, unsigned int, unsigned int, unsigned int)
  [1:10] libc.so.6 0xffffafed6ba0
Aborted (core dumped)
```

**Comment by evan-charmworks** [comment]
This failure is bizarre. I can reproduce it even on multicore, on a Jetson Orin Nano. I don't know why ARM platforms are so predisposed to it.

@stwhite91 Do you know what I should look for to see what's going wrong? I think CharmDebug and verbose printing is the kind of approach this needs.

```
$ ./megampi +p2 +vp2 +LBDebug 1
Charm++: standalone mode (not using charmrun)
Charm++> Running in Multicore mode: 2 threads (PEs)
Converse/Charm++ Commit ID: v7.1.0-devel-297-gfe3889dfc
Charm++ built with internal error checking enabled.
Do not use for performance benchmarking (build without --enable-error-checking to do so).
Charm++> scheduler running in netpoll mode.
CharmLB> Verbose level 1, load balancing period: -1 seconds
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 6 cores x 1 PUs = 6-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
[0] No TreeLB configuration file found. Choosing a default configuration.
[0] TreeLB: Using PE_Root tree with: GreedyRefine
        Using 0 as root
        Test PE Speed: false
[0] Testing: Testing...
--------- Started LB step 0 ---------
[0] num_procs=2 num_objs=2
[0] obj loads: min=0.000985 mean=0.001392 max=0.001799
[0] proc loads: min=0.001581 mean=0.002062 max=0.002542
[0] GreedyRefine: greedy maxload is 0.002396, tolerance set to 1.000000
[0] strategy GreedyRefine time=0.000012 secs, maxLoad after strategy=0.002396, num_migrations=2 migrations_sum_hops=0
--------- Finished LB step 0 ---------
------------- Processor 1 Exiting: Called CmiAbort ------------
Reason: TCharm has not been initialized!

[0] lb time = 0.000275
[1] Stack Traceback:
  [1:0] megampi 0xaaaac251648c
  [1:1] megampi 0xaaaac22a9bd0 TCHARM_Migrate
  [1:2] megampi 0xaaaac233b5bc AMPI_Migrate
  [1:3] megampi 0xaaaac22a3fc0 MPI_Tester::testMigrate()
  [1:4] megampi 0xaaaac22a46c8 AMPI_Main
  [1:5] megampi 0xaaaac23113b0 AMPI_threadstart
  [1:6] megampi 0xaaaac22a7e24
  [1:7] megampi 0xaaaac24b91a4 CthStartThread(unsigned int, unsigned int, unsigned int, unsigned int)
  [1:8] libc.so.6 0xffffafed6ba0
Charm++ fatal error:
TCharm has not been initialized!

[1] Stack Traceback:
  [1:0] megampi 0xaaaac25162e8 LrtsAbort(char const*)
  [1:1] megampi 0xaaaac2516394 CmiAbortHelper(char const*, char const*, char const*, int, int)
  [1:2] megampi 0xaaaac251648c
  [1:3] megampi 0xaaaac22a9bd0 TCHARM_Migrate
  [1:4] megampi 0xaaaac233b5bc AMPI_Migrate
  [1:5] megampi 0xaaaac22a3fc0 MPI_Tester::testMigrate()
  [1:6] megampi 0xaaaac22a46c8 AMPI_Main
  [1:7] megampi 0xaaaac23113b0 AMPI_threadstart
  [1:8] megampi 0xaaaac22a7e24
  [1:9] megampi 0xaaaac24b91a4 CthStartThread(unsigned int, unsigned int, unsigned int, unsigned int)
  [1:10] libc.so.6 0xffffafed6ba0
Aborted (core dumped)
```

**Comment by evan-charmworks** [comment]
Verbose log with ampiimpl, tcharm_impl, ckarray, and cklocation debug prints enabled: [ampi-tcharm-not-initialized-abort-verbose.txt](https://github.com/UIUC-PPL/charm/files/12022437/ampi-tcharm-not-initialized-abort-verbose.txt)

**Comment by stwhite91** [comment]
Is this the first test of any AMPI migration? Does megampi +p2 +vp1 pass?

**Comment by evan-charmworks** [comment]
Yes, it's the first test. `megampi +p2 +vp1` fails consistently.

```
$ ./megampi +p2 +vp1 +LBDebug 1
Charm++: standalone mode (not using charmrun)
Charm++> Running in Multicore mode: 2 threads (PEs)
Converse/Charm++ Commit ID: v7.1.0-devel-297-gfe3889dfc
Charm++ built with internal error checking enabled.
Do not use for performance benchmarking (build without --enable-error-checking to do so).
Charm++> scheduler running in netpoll mode.
CharmLB> Verbose level 1, load balancing period: -1 seconds
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 6 cores x 1 PUs = 6-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
[0] No TreeLB configuration file found. Choosing a default configuration.
[0] TreeLB: Using PE_Root tree with: GreedyRefine
        Using 0 as root
        Test PE Speed: false
[0] Testing: Testing...
--------- Started LB step 0 ---------
[0] num_procs=2 num_objs=1
[0] obj loads: min=0.000745 mean=0.000745 max=0.000745
[0] proc loads: min=0.000080 mean=0.000644 max=0.001209
[0] GreedyRefine: greedy maxload is 0.000824, tolerance set to 1.000000
[0] strategy GreedyRefine time=0.000011 secs, maxLoad after strategy=0.000824, num_migrations=1 migrations_sum_hops=0
--------- Finished LB step 0 ---------
[0] lb time = 0.000129
------------- Processor 1 Exiting: Called CmiAbort ------------
Reason: TCharm has not been initialized!

[1] Stack Traceback:
  [1:0] megampi 0xaaaad298648c
  [1:1] megampi 0xaaaad2719bd0 TCHARM_Migrate
  [1:2] megampi 0xaaaad27ab5bc AMPI_Migrate
  [1:3] megampi 0xaaaad2713fc0 MPI_Tester::testMigrate()
  [1:4] megampi 0xaaaad27146c8 AMPI_Main
  [1:5] megampi 0xaaaad27813b0 AMPI_threadstart
  [1:6] megampi 0xaaaad2717e24
  [1:7] megampi 0xaaaad29291a4 CthStartThread(unsigned int, unsigned int, unsigned int, unsigned int)
  [1:8] libc.so.6 0xffff822d9ba0
Charm++ fatal error:
TCharm has not been initialized!

[1] Stack Traceback:
  [1:0] megampi 0xaaaad29862e8 LrtsAbort(char const*)
  [1:1] megampi 0xaaaad2986394 CmiAbortHelper(char const*, char const*, char const*, int, int)
  [1:2] megampi 0xaaaad298648c
  [1:3] megampi 0xaaaad2719bd0 TCHARM_Migrate
  [1:4] megampi 0xaaaad27ab5bc AMPI_Migrate
  [1:5] megampi 0xaaaad2713fc0 MPI_Tester::testMigrate()
  [1:6] megampi 0xaaaad27146c8 AMPI_Main
  [1:7] megampi 0xaaaad27813b0 AMPI_threadstart
  [1:8] megampi 0xaaaad2717e24
  [1:9] megampi 0xaaaad29291a4 CthStartThread(unsigned int, unsigned int, unsigned int, unsigned int)
  [1:10] libc.so.6 0xffff822d9ba0
Aborted (core dumped)
```

[ampi-megampi-p2-vp1-tcharm-not-initialized-abort-verbose.txt](https://github.com/UIUC-PPL/charm/files/12023074/ampi-megampi-p2-vp1-tcharm-not-initialized-abort-verbose.txt)

**Comment by stwhite91** [comment]
Hmm, I would expect that the simplest hello world type of program with a call to AMPI_Migrate() would also fail with +p2 +vp1 then?

**Comment by evan-charmworks** [comment]
tests/ampi/privatization/control-cxx sometimes fails.

[ampi-arm64-simple-success.txt](https://github.com/UIUC-PPL/charm/files/12023288/ampi-arm64-simple-success.txt)
[ampi-arm64-simple-failure.txt](https://github.com/UIUC-PPL/charm/files/12023289/ampi-arm64-simple-failure.txt)

**Comment by stwhite91** [comment]
That's helpful. It would be good to test a simple TCharm migration code. Could also isolate Isomalloc vs not, and any privatization techniques.  I don't think any standalone TCharm tests exist right now. If that passes it would tell us that the issue is in AMPI and adding more debug prints in AMPI's PUP would help, otherwise we'll need to debug TCharm and below.

**Review by ericjbohm — APPROVED** [review]

**Review by matthiasdiener — APPROVED** [review]

**Pull request merged**
