### PR TITLE
Use Zcpy API code path for non-RDMA layers

### PR DESCRIPTION
**Pull request by nitbhat**
This PR was introduced in order to make layers without RDMA support (like netlrts) more maintainable, since maintaining a separate code path for the copy based approach in the entry method API was beginning to get very troublesome when I was working on the delayed Rget functionality. Primarily, this PR removes the 'CMK_ONESIDED_IMPL' guards at several places. With this change, the Entry method API for non-RDMA layers uses the direct API underneath, much like the other RDMA layers except for the fact that the non-RDMA layers use the copy based Direct API underneath. 

Since my account on Summit is not active, I wasn't able to test `pami-linux-ppc64le`. If we decide in the upcoming core meeting to maintain that layer, it'll be great if someone with an active account can test that layer. Since it's a non-LRTS layer, I'm guessing there'll be some build issues there.

### CODE REVIEW

**Comment by minitu** [comment]
@nitbhat Could you list all the non-RDMA layers for reference?

**Comment by nitbhat** [comment]
> @nitbhat Could you list all the non-RDMA layers for reference?

Yes, currently, the following have CMK_ONESIDED_IMPL disabled. (either because they lack RDMA support or because there is a weird underlying bug):

1. netlrts 
2. gni-crayxe
3. pami
4. pamilrts
5. uth

Not including sim and shmem because they are being removed.

**Comment by evan-charmworks** [comment]
> > @nitbhat Could you list all the non-RDMA layers for reference?
> 
> Yes, currently, the following have CMK_ONESIDED_IMPL disabled. (either because they lack RDMA support or because there is a weird underlying bug):
> 
> 2. gni-crayxe

Did we ever try enabling CMK_ONESIDED_IMPL for Cray XE after merging #3003? Could that have been the reason for the issue?

**Review by evan-charmworks — DISMISSED** [review]

**Review by minitu — DISMISSED** [review]

**Comment by nitbhat** [comment]
> > > @nitbhat Could you list all the non-RDMA layers for reference?
> > 
> > 
> > Yes, currently, the following have CMK_ONESIDED_IMPL disabled. (either because they lack RDMA support or because there is a weird underlying bug):
> > 
> > 1. gni-crayxe
> 
> Did we ever try enabling CMK_ONESIDED_IMPL for Cray XE after merging #3003? Could that have been the reason for the issue?

That's a very good point. I don't think I have, I think I lost access to BW. Definitely something worth trying.

**Comment by nitbhat** [comment]
`examples/charm++/zerocopy/entry_method_post_api/unreg` is crashing for some reason: (can't reproduce this on my local machine). 

```2020-11-11T21:16:02.2230340Z ../../../../../../bin/testrun  +p4 ./simpleZeroCopy 32 +balancer GreedyLB 
2020-11-11T21:16:02.2354150Z Running command:  ./simpleZeroCopy  +p4 32 +balancer GreedyLB
2020-11-11T21:16:02.2354530Z 
2020-11-11T21:16:02.3897310Z ../../../../../../bin/testrun: line 62: 47896 Segmentation fault: 11  ./charmrun "$@"
2020-11-11T21:16:02.3897820Z 
2020-11-11T21:16:02.3898070Z real	0m0.157s
2020-11-11T21:16:02.3898410Z user	0m0.306s
2020-11-11T21:16:02.3898660Z sys	0m0.249s
2020-11-11T21:16:02.3899070Z make[6]: *** [test] Error 139
2020-11-11T21:16:02.3900290Z make[5]: *** [test-simpleZeroCopy] Error 2
2020-11-11T21:16:02.3901170Z make[4]: *** [test-unreg] Error 2
2020-11-11T21:16:02.3902010Z make[3]: *** [test-entry_method_post_api] Error 2
2020-11-11T21:16:02.3902950Z make[2]: *** [test-zerocopy] Error 2
2020-11-11T21:16:02.3904190Z make[1]: *** [test-charm++] Error 2
2020-11-11T21:16:02.3904540Z make: *** [test] Error 2```

**Review by minitu — APPROVED** [review]

**Review by evan-charmworks — APPROVED** [review]

**Pull request merged**
