### PR TITLE
citation.cff: add BibTeX entries as comments

### PR DESCRIPTION
**Pull request by matthiasdiener**
Author listing in the Zenodo entry follows Zenodo's own list (minus putting Sanjay first).

### CODE REVIEW

**Comment by matthiasdiener** [comment]
Nota bene that Zenodo's BibTeX generator creates illegal bibtex entries...

**Comment by matthiasdiener** [comment]
> Where is that order visible to others besides this file? In our zenodo webpage?
> 
> Also, is the order arbitrary? Not sure if there was a discussion about this in core, but maybe we want a non-arbitrary order, like chronological or something else.

Yes, it is the same order as here: https://zenodo.org/record/3370874#.XW65yS2ZNTY

We discussed this in core, but we didn't really figure out how the order was generated (apart from some general notion of "number of contributions").

**Comment by rbuch** [comment]
Note that we can also modify the listing (in terms of ordering and in terms of who is included) that Zenodo uses to whatever we want it to be.

It may make more sense to put the BibTeX entries under the `notes` key of a CFF file so that it has some semantic meaning rather than putting them in as comments.

**Comment by matthiasdiener** [comment]
> It may make more sense to put the BibTeX entries under the `notes` key of a CFF file so that it has some semantic meaning rather than putting them in as comments.

Converted to notes.

**Comment by juanjgalvez** [comment]
This is fine by me, but maybe we should check that there is consensus in core?

**Comment by rbuch** [comment]
> Nota bene that Zenodo's BibTeX generator creates illegal bibtex entries...

Just to check, I assume the entries you've added to the CITATION.cff file are not the same as these illegal bibtex entries, right?

**Comment by matthiasdiener** [comment]
> > Nota bene that Zenodo's BibTeX generator creates illegal bibtex entries...
> 
> Just to check, I assume the entries you've added to the CITATION.cff file are not the same as these illegal bibtex entries, right?

Yes, that's correct.

**Comment by matthiasdiener** [comment]
Author order changed to Zenodo's (alphabetically with Sanjay first).

**Pull request merged**
