### PR TITLE
Clean up CMK_MOD_NAME_ALLCAPS on ppc64le with GCC

### PR DESCRIPTION
**Pull request by evan-charmworks**

### CODE REVIEW

**Comment by minitu** [comment]
`./buildold charm++ pamilrts-linux-ppc64le smp gcc -j --with-production` works fine, whereas
the CMake build `./build charm++ pamilrts-linux-ppc64le smp gcc -j --with-production` errors out:

```
[100%] Linking CXX executable bin/hello
/ccs/home/jchoi/work/charm-github/pamilrts-linux-ppc64le-smp-gcc/bin/../lib/libhwloc_embedded.a(topology-linux.o): In function `cmi_hwloc_linux_get_tid_last_cpu_location':
/ccs/home/jchoi/work/charm-github/pamilrts-linux-ppc64le-smp-gcc/hwloc-prefix/src/hwloc/hwloc/topology-linux.c:(.text+0xd80): undefined reference to `_fill'
/ccs/home/jchoi/work/charm-github/pamilrts-linux-ppc64le-smp-gcc/bin/../lib/libhwloc_embedded.a(topology-linux.o): In function `hwloc_linux_foreach_proc_tid_get_last_cpu_location_cb':
/ccs/home/jchoi/work/charm-github/pamilrts-linux-ppc64le-smp-gcc/hwloc-prefix/src/hwloc/hwloc/topology-linux.c:(.text+0x432c): undefined reference to `_fill'
/usr/bin/ld: link errors found, deleting executable `bin/hello'
collect2: error: ld returned 1 exit status
Fatal Error by charmc in directory /ccs/home/jchoi/work/charm-github/pamilrts-linux-ppc64le-smp-gcc
   Command g++ -rdynamic CMakeFiles/hello.dir/tests/charm++/simplearrayhello/hello.C.o moduleinit113343.o -L/ccs/home/jchoi/work/charm-github/pamilrts-linux-ppc64le-smp-gcc/bin/../lib -lckmain -lck -lmemory-default -lthreads-default -lconv-machine -lconv-core -ltmgr -lconv-util -lconv-partition -lhwloc_embedded -lm -lmemory-default -lthreads-default -lldb-rand -lconv-ldb -lckqt -lckqt -lz -ldl -lmoduleNDMeshStreamer -lmodulecompletion -L /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-5/spectrum-mpi-10.3.1.2-20200121-p6nrnt6vtvkn356wqg6f74n6jspnpjd2/lib/pami_port -L /autofs/nccs-svm1_sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/xl-16.1.1-5/spectrum-mpi-10.3.1.2-20200121-p6nrnt6vtvkn356wqg6f74n6jspnpjd2/lib/pami_port -lcollectives -L /usr/lib/powerpc64le-linux-gnu -lpami -libverbs -lstdc++ -lc -ldl -lrt -lpthread -lz -lm /ccs/home/jchoi/work/charm-github/pamilrts-linux-ppc64le-smp-gcc/bin/../lib/conv-static.o -o bin/hello returned error code 1
charmc exiting...
make[2]: *** [bin/hello] Error 1
make[1]: *** [CMakeFiles/hello.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by minitu** [comment]
I see the same error with master, so not a problem introduced by this PR.

**Comment by evan-charmworks** [comment]
According to https://github.com/numpy/numpy/issues/16172#issuecomment-664064330, this `_fill` symbol can be provided by linking in `-lxl`.

**Review by minitu — APPROVED** [review]
Hm not sure why IBM XL should be linked (maybe hwloc was compiled with XL?), but created an issue for this in #3152.
I think this PR itself is good as it fixes `./buildold`.

**Review by stwhite91 — APPROVED** [review]

**Pull request merged**
