### PR TITLE
Add support for ICX compiler instead of DPCPP

### PR DESCRIPTION
**Pull request by minitu**
As of Intel oneAPI 2022, Clang is no longer supported in the compiler toolchain.
This commit fixes the issues that arise from this change (and uses ICX instead of DPCPP).
Build tested on Intel DevCloud with NAMD.
Example build command: `./build charm++ multicore-linux-x86_64 icx -j --with-production`

### CODE REVIEW

**Review by jszaday — APPROVED** [review]
Charm++ now builds with ICX on a machine that does not have `clang++`, thanks!

**Comment by evan-charmworks** [comment]
Is it worth leaving DPCPP support for versions of oneAPI prior to 2022, in case users don't have access to the newest version?

**Comment by jszaday** [comment]
> Is it worth leaving DPCPP support for versions of oneAPI prior to 2022, in case users don't have access to the newest version?

I think `icpx` has been included with every version of ICX. So, any machine that has `icx` should have `icpx` as well. For example,

```
mirzam :: ~ % icpx -v                                                                                                                                                                        
Intel(R) oneAPI DPC++/C++ Compiler 2021.4.0 (2021.4.0.20210924)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2021.4.0/linux/bin
Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**Comment by minitu** [comment]
@evan-charmworks I think it is cleaner to just have an ICX build available, I believe `icpx` is basically identical to `dpcpp` (which is why the DPC++ build of NAMD is also able to use the ICX build of Charm++), and as Justin said `icpx` (C++ compiler) is available with `icx` (C compiler). This is also the input from the Intel developers working with me on the NAMD DPC++ porting effort.

**Review by evan-charmworks — APPROVED** [review]

**Pull request merged**
