### PR TITLE
Cleanup CkSyncBarrier code

### PR DESCRIPTION
**Pull request by rbuch**
Fixes stylistic issues, particularly with variable and method names. Additionally, changes the semantics of the kick epoch, previously it would trigger the barrier when it was greater than or equal to the current epoch, now it must be strictly greater than the current epoch to trigger the barrier (which mirrors the behavior of regular AtSync elements).

### CODE REVIEW

**Comment by evan-charmworks** [comment]
Is "Kick" a standard term? What exactly does it mean in this context?

**Comment by rbuch** [comment]
> Is "Kick" a standard term? What exactly does it mean in this context?

It is a standard term (at least in related contexts, like watchdog timers, although the purpose is reversed there). The point here is to kick PEs with no AtSync elements on them so that they participate in the AtSync barrier (so that they can do things like participate in a group reduction to start load balancing). When there's no AtSync element on the PE, nothing local is going to trigger it, so this kick needs to be propagated in order to do so.

If there are any naming or other suggestions, I'd love to hear them, I want to make this as clear as possible.

**Comment by evan-charmworks** [comment]
Some ideas: prompt, trigger, induce, invoke, initiate

**Comment by rbuch** [comment]
> Some ideas: prompt, trigger, induce, invoke, initiate

I think I prefer "kick" over these since it seems more clearly distinct from "triggering the barrier," which seems like the most natural term to call reaching the barrier and executing the receivers, and it has the existing similar usage in the watchdog context.

**Review by stwhite91 — DISMISSED** [review]

**Review by epmikida — APPROVED** [review]

**Review by evan-charmworks — APPROVED** [review]

**Review by epmikida — APPROVED** [review]

**Pull request merged**
