### PR TITLE
AMPI cleanup: pass ampiParent* around rather than always calling getAmpiParent()

### PR DESCRIPTION
**Pull request by stwhite91**
Make all wait() routines take a parent pointer and return a refreshed one
after possibly suspending and migrating.

*Original date: 2019-05-03 19:13:11*
*Original PR: https://charm.cs.illinois.edu/gerrit/3807*

---

Change-Id: If8c8408a2402a61f4588bab24ec5709dfde878a9

### CODE REVIEW

**Comment by evan-charmworks** [comment]
This needs a force push to eliminate all commits but bad7c077c7a011856b63bb7d30f0f9bac43e1f31

**Comment by stwhite91** [comment]
Ready for review

**Comment by evan-charmworks** [comment]
How does this patch interact with the need for pointer refreshing after migration? Passing the parent pointer around on the stack could leave more opportunities for it to become stale, though it may not be a problem anywhere.

**Comment by stwhite91** [comment]
> How does this patch interact with the need for pointer refreshing after migration? Passing the parent pointer around on the stack could leave more opportunities for it to become stale, though it may not be a problem anywhere.

True, maybe it's better to have all the wait() routines be CMI_WARN_UNUSED and return an updated ampiParent pointer, that way the caller passes in a pointer and gets back a refreshed one.

**Comment by evan-charmworks** [comment]
This PR still has stale commits mixed in. Assuming that all changes are contained in the `AMPI cleanup: pass ampiParent* around rather than always calling getAmpiParent()` patch and later merge commits don't change the substance of the PR further, these steps should fix it:

```
git checkout review/samuel_white/3807
# or, if that doesn't work
git checkout --track origin/review/samuel_white/3807

# reset the branch pointer to the commit we want
git reset --hard b47c33761b5c507391f3dad8237a7946b8b0585c

# use git rebase --onto to eliminate the stale changes mixed in
git rebase --onto master HEAD~1

# at this point use git log, gitk, etc to verify the PR
git log -2

# force push
git push -f origin review/samuel_white/3807
```

**Comment by matthiasdiener** [comment]
Fails in megampi: 
```
../../../bin/testrun  ./pgm +p1 +vp2  ++local +setcpuaffinity +isomalloc_sync +CmiSleepOnIdle
Charmrun> scalable start enabled. 
Charmrun> started all node programs in 0.005 seconds.
Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
Charm++> The comm. thread both sends and receives messages
Converse/Charm++ Commit ID: v6.9.0-471-g5f463798b
Charm++> Synchronizing isomalloc memory region...
Charm++> Consolidated Isomalloc memory region: 0x440000000 - 0x7f5e80000000 (133538816 MB).
Charm++> scheduler running in netpoll mode.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> cpu affinity enabled. 
Charm++> Running on 1 hosts (1 sockets x 1 cores x 2 PUs = 2-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
CharmLB> RandCentLB created.
[0] Testing: Testing...
------------- Processor 0 Exiting: Called CmiAbort ------------
Reason: In AMPI_Waitall, all requests should have completed by now!
[0] Stack Traceback:
  [0:0]   [0x642a1b]
  [0:1] PMPI_Waitall+0x35d  [0x507cfd]
  [0:2] _ZN10MPI_Tester4testEv+0x3a2  [0x4c558c]
  [0:3] AMPI_Main_cpp+0xde  [0x4c6191]
  [0:4] AMPI_threadstart+0xc9  [0x4e6259]
  [0:5]   [0x4ca457]
  [0:6] CthStartThread+0x17  [0x63fc67]
  [0:7] make_fcontext+0x2f  [0x6404ff]```

**Comment by stwhite91** [comment]
> Fails in megampi:
> 
> ```
> ../../../bin/testrun  ./pgm +p1 +vp2  ++local +setcpuaffinity +isomalloc_sync +CmiSleepOnIdle
> Charmrun> scalable start enabled. 
> Charmrun> started all node programs in 0.005 seconds.
> Charm++> Running in SMP mode: 1 processes, 1 worker threads (PEs) + 1 comm threads per process, 1 PEs total
> Charm++> The comm. thread both sends and receives messages
> Converse/Charm++ Commit ID: v6.9.0-471-g5f463798b
> Charm++> Synchronizing isomalloc memory region...
> Charm++> Consolidated Isomalloc memory region: 0x440000000 - 0x7f5e80000000 (133538816 MB).
> Charm++> scheduler running in netpoll mode.
> CharmLB> Load balancer assumes all CPUs are same.
> Charm++> cpu affinity enabled. 
> Charm++> Running on 1 hosts (1 sockets x 1 cores x 2 PUs = 2-way SMP)
> Charm++> cpu topology info is gathered in 0.000 seconds.
> CharmLB> RandCentLB created.
> [0] Testing: Testing...
> ------------- Processor 0 Exiting: Called CmiAbort ------------
> Reason: In AMPI_Waitall, all requests should have completed by now!
> [0] Stack Traceback:
>   [0:0]   [0x642a1b]
>   [0:1] PMPI_Waitall+0x35d  [0x507cfd]
>   [0:2] _ZN10MPI_Tester4testEv+0x3a2  [0x4c558c]
>   [0:3] AMPI_Main_cpp+0xde  [0x4c6191]
>   [0:4] AMPI_threadstart+0xc9  [0x4e6259]
>   [0:5]   [0x4ca457]
>   [0:6] CthStartThread+0x17  [0x63fc67]
>   [0:7] make_fcontext+0x2f  [0x6404ff]```
> ```

Fixed

**Pull request merged**
