### PR TITLE
Delete duplicate cmake variable, and fix another

### PR DESCRIPTION
**Pull request by nilsleiffischer**

### CODE REVIEW

**Review by matthiasdiener — DISMISSED** [review]
Thanks!

**Review by NK-Nikunj — APPROVED** [review]
Oops, that was a mistake from my end. Thanks for looking into it. LGTM!

**Comment by nilsleiffischer** [comment]
Pushed another small fix

**Review by matthiasdiener — APPROVED** [review]

**Review by NK-Nikunj — APPROVED** [review]
Thanks!

**Pull request merged**
