### PR TITLE
charmc: make sure to link against pthread when using CkLoop

### PR DESCRIPTION
**Pull request by matthiasdiener**
Should help with issues such as the one seen here: https://github.com/spack/spack/pull/15666 @s-sajid-ali

### CODE REVIEW

**Comment by jcphill** [comment]
Does this work on Windows?

**Comment by matthiasdiener** [comment]
> Does this work on Windows?

That's a good point. Is CkLoop even supported on Windows? We could also restrict this to non-SMP mode (when pthreads is actually used).

**Comment by matthiasdiener** [comment]
> > Does this work on Windows?
> 
> That's a good point. Is CkLoop even supported on Windows? We could also restrict this to non-SMP mode (when pthreads is actually used).

Fixed in the updated patch.

**Comment by evan-charmworks** [comment]
If you grep for pthread in src/arch, there is a lot of `-lpthread`. Should `-pthread` go there instead of charmc?

**Comment by matthiasdiener** [comment]
> If you grep for pthread in src/arch, there is a lot of `-lpthread`. Should `-pthread` go there instead of charmc?

These seem to be mostly for SMP support. The issue here is that we need pthread for non-SMP mode, but only when using CkLoop. I think putting this in multiple src/arch files would cause lots of duplication there.

**Pull request merged**
